### ISSUE TITLE
code - button components

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#1]
## `todo`

- [x] code - button component
   - `@input` 📦 [buttons_v0.0.2](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1374-6906&t=Ox51Ohm1m5cMB0nq-4) from [issue#71](https://github.com/dat-ecosystem/organization/issues/71)
   - [x] code separate components for buttons
   - `@output` 📦 [button_v0.0.1](https://github.com/Mehrabbruno/dat-ecosystem/commit/586067b43eecef85e5bb55cabbcea42bcd20ef9b) from [comment]()

---

- [x] update button_v0.0.1
   - `@input` 📦 [button_v0.0.1](https://github.com/Mehrabbruno/dat-ecosystem/commit/586067b43eecef85e5bb55cabbcea42bcd20ef9b) 
   - [x] update the button width for it to work properly in parent repo
   - `@output` 📦 [button_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/fa6809c65ba3cfda8f3c56d31c9a05868c2fcab4) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.05.20`

- code - button component  - `1h32min`
   - create github repo - `25min`
   - code icon_buttons
   - code text_buttons
   - code logo_buttons
   - `@output` 📦 [button_v0.0.1](https://github.com/Mehrabbruno/dat-ecosystem/commit/586067b43eecef85e5bb55cabbcea42bcd20ef9b)
- update button_v0.0.1 
   - trying to fix path issue - `33min`
   - update the button width for it to work properly in parent repo
   - create and update tasks, worklog etc  - `27min`
   - `@output` 📦 [button_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/fa6809c65ba3cfda8f3c56d31c9a05868c2fcab4)

---

## worklog 

---

## feedback

- created button components
- updated styles of button component to fit responsively in parent container styles (i.e. responsive /navbar)

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.05.19`**

code looks good. i linked the issue above to its parent issue. output should be used in `page component` issue as an input and also listed in dat-website issue. the issues all need some updates, but if you accept the invite you should hopefully be able to edit the issues.

## otherwise
1. the code isn't yet in `standardjs` style (e.g. 2 spaced + `function fn_name () { }` instead of `function fn_name(){ }`
2. per navbar instance we create, there should be just one style sheet, so it should be like:
```js

function navbar(){
    // CSS Boiler Plat
    const sheet = new CSSStyleSheet
    const theme = get_theme()
    sheet.replaceSync(theme)

**Comment by Mehrabbruno** [comment]
### tasks - `2023.05.26`

- update button_v0.0.2
   - read feedback - `7min`
   - change buttons file structure - `1h7min`
   - create worklog comment, task, issues and pull request - `39min`
   - `@output` 📦 [button_v0.0.3](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/ab5f1be017c22d839b2823533b2979216f09c903)

---

## worklog 

---

## feedback

- updated buttons structure

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.3`

- update button_v0.0.3 - 31min
   - coded - small icon button
   - coded - small text button
   - updated - theme variables
   - updated - icon toggle
   - create worklog comment, and task- `min`
   - `@output` 📦 [button_v0.0.4](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-a86de8010d972be7365507d0a6c452bcbbd536fef72ad4a3ec6ce8c84a8fb0bc)

---

## worklog 

[worklog-149](https://youtu.be/l0yaPv_6oLI)

---

## feedback

- created multiple new buttons 
- changed theme variables compo

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.08.06`**

Looks good.
Some coding hints again for the different buttons, e.g.

### e.g. icon_button
```js
function icon_button (props) {
    let {src, src_active} = props

    const el = document.createElement('div')
    const shadow = el.attachShadow({mode:'closed'})

    const icon_button = document.createElement('div')
    icon_button.classList.add('icon_btn')

    const icon = document.createElement('img')
    icon.src = src
    icon_button.append(icon)

    // Toggle Icon
    if(src_active){
        let activeState = true;
        icon_button.onclick = (e) =>{
            ;(activeState)?icon.src = src_active: icon.src = src
            activeState = !activeState
            toggle_class(e)
        }
    }else{
        // Toggle Class
        icon_button.onclick = (e) => toggle_class(e)
    }

    const style = document.createElement('style')
    style.textContent = get_theme()

    shadow.append(icon_button, style)
    shadow.adoptedStyleSheets = [sheet]
    return el
}
```
could become:
```js
function icon_button (props) {
  const { src, src_active, state = { active: true } } = props

  const el = document.createElement('div')
  const shadow = el.attachShadow({ mode: 'closed' })
  shadow.innerHTML = `
    <div class="icon_btn"><img></div>
    <style>${get_theme()}</style>
  `
  const [icon_button] = shadow.children
  const [icon] = icon_button.children
  
  icon_button.onclick = toggle_class
  if (state.active) toggle_class()

  shadow.adoptedStyleSheets = [sheet]
  return el
  function toggle_class (e) {
    icon_button.classList.toggle('active')
    state.active = !state.active
    icon.src = state.active ? src_active : src
  }
}
```

### e.g. logo_button
```js
function logo_button (props) {
  const { src, src_active, state = { active: true } } = props

  const el = document.createElement('div')
  const shadow = el.attachShadow({ mode: 'closed' })
  shadow.innerHTML = `<div class="logo_button">
    <img src="`${prefix}/logo.png`">
    <span>DAT ECOSYSTEM</span>
  </div><style>${get_theme()}</style>`    
  const [logo_button] = shadow.children
  
  logo_button.onclick = toggle_class
  if (state.active) toggle_class()

  shadow.adoptedStyleSheets = [sheet]
  return el
  function toggle_class (e) {
    logo_button.classList.toggle('active')
    state.active = !state.active
  }
}
```

### e.g. sm_icon_button_alt
```js
function sm_icon_button_alt (props) {
  const { src, src_active, state = { active: true } } = props

  const el = document.createElement('div')
  const shadow = el.attachShadow({ mode: 'closed' })
  shadow.innerHTML = `
    <div class="sm_icon_button_alt"><img></div>
    <style>${get_theme()}</style>
  `    
  const [sm_icon_button_alt] = shadow.children
  const [icon] = icon_button.children
  
  sm_icon_button_alt.onclick = toggle_class
  if (state.active) toggle_class()

  shadow.adoptedStyleSheets = [sheet]
  return el
  function toggle_class (e) {
    sm_icon_button_alt.classList.toggle('active')
    state.active = !state.active
    icon.src = state.active ? src_active : src
  }
}
```

### e.g. text_button
```js
function text_button (props) {
  const { text, src, src_active, state = { active: true } } = props

  const el = document.createElement('div')
  const shadow = el.attachShadow({ mode: 'closed' })
  shadow.innerHTML = `<div class="text_button">
    ${text}
  </div><style>${get_theme()}</style>`    
  const [text_button] = shadow.children
  
  text_button.onclick = toggle_class
  if (state.active) toggle_class()

  shadow.adoptedStyleSheets = [sheet]
  return el
  function toggle_class (e) {
    icon_button.classList.toggle('active')
    state.active = !state.active
  }
}
```

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.10`

- update button_v0.0.4 - `2h24min`
   - coded - small icon button
   - added - dropdown with select options
   - create comment, and task - `18min`
   - create worklog - `11min`
   - read feedback on dat-website - `17min`
   - `@output` 📦 [button_v0.0.5](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/a56d67719e31e276fd606660c518a0b21b1896e8#diff-787aadfd200d8db1028fd79d1ea665f7c7262457cbcc8dee726b301fe2c73167)

---

## worklog 

[worklog-151](https://youtu.be/Uedwq1RYPz8)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.10`**

Will just add some code snippets for how to write  things more concise and slightly faster

Anyay, reading the code i am not sure what the component is supposed to do.
Is it bug free and working?

My guess is the component has a "submit" button and is supposed to submit the data
the options currently present. Can there be one or many options?
If it is always three, i would probably list them separately, but i will try to refactor as if it could be 10 or 100 options dynamically changing...

**IMPORTANT:** The DOM is much slower than javascript, thus one rule is to never use the DOM to hold your STATE, instead store in in JS

```js

    // ...
    
    const STATE = new Map()
    const singleselect = true // not multiselect
    
    // TEMPLATE: set main component template
    shadow.innerHTML = `
        <div class="select_button_wrapper bottom">
            <div class="option_wrapper">
              ${['ACTIVE', 'UNACTIVE', PAUSED'].map(txt => {
                return `<div class="option"><span>${txt}</span></div>`
              }).join('')}
            </div>
            <div class="button_wrapper">
                <span class="button_name">${'STATUS: '}</span>
                <span class="selected_option">${'NULL'}</span>
                <span class="arrow_icon"><img src=${icon_arrow_up} /></span>
            </div>
        </div>
        <style> ${get_theme} </style>
    `
    // REFERENCES: prepare references to all relevant elements
    const [select_button_wrapper] = shadow.children
    const [{children: [...options]], select_toggle_btn] = select_button_wrapper.children
    const [,selected_option] = select_toggle_btn.children

    // DO SOME MORE STUFF:, e.g. setup, attach event listeners, etc...
    
    
    // 0. Use event delegation
    document.addEventListener('click', onclick_unfocus)
    // 1. define the rest of the component, e.g. use element references
    select_toggle_btn.onclick = onclick_select_toggle_btn
    // 2. Attach click event listener to each .option div
    options.forEach((option, i) => {
      const [content] = option.children
      const active_node = content.cloneNode(true)
      const inactive_node = document.createTextNode('Null')
      selected_option.append(indicate_active)
      STATE.set(option, { active: false, active_node, inactive_node })
      option.onclick = onclick_option
    })
    // ...
    
    return el
    // -------------------------------------
    // NOW DEFINE ALL HELPER FUNCTIONS (after the return)
    // -------------------------------------
    function onclick_unfocus (event) {
      // here .addEventListener is great, because .onclick would get overriden
      console.log('unfocus', e.target.className) // some shadow dom element
    }
    function onclick_select_toggle_btn (event) {
      event.stopPropagation()
      const actives = [STATE.values()].filter(({active}) => active).map(({text}) => text) 
      console.log('SELECTED OPTIONS:', actives)
      select_toggle_btn.classList.toggle('active')
    }
    function onclick_option (event) {
      event.stopPropagation()
      const option = event.currentTarget
      const status = STATE.get(option)
      if (status.active) return active_option = deactivate_option(option, status)
      if (singleselect && (active_option !== option)) {
        deactivate_option(active_option, STATE.get(active_option))
      }
      active_option = activate_option(option, status)
      select_button_wrapper.classList.toggle('active')
    }
    function deactivate_option (option, status) {
      option.classList.remove('active')
      status.active = false
      status.active_node.replaceWith(status.inactive_node)
    }
    functin activate_option (option, status) {
      option.classList.add('active')
      status.active = true
      status.inactive_node.replaceWith(status.active_node)
      return option
    }
```

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.06`

- update button_v0.0.5
   - update - select_button - `1h`
   - update - icon_button - `15min`
   - update - text_button - `20min`
   - update - sm_icon_button - `18min`
   - update - sm_icon_button_alt - `17min`
   - create - worklog comment, and task- `14min`
   - `@output` 📦 [`button_v0.0.5`](https://github.com/dat-ecosystem/dat-ecosystem/commit/9081561da793ce4c4240db22178bc2ae49a87863#diff-bd4138be9465c592c9d9c8cc58f895c5d2936b9cb2b02f2ef459f4443aad1a28)

---

## worklog 

[worklog-160](https://youtu.be/vEjAzVv_N4U)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- update button_v0.0.6 - `18min`
   - update - select_button
   - create - worklog comment, and task- `11min`
   - `@output` 📦 [button_v0.0.7](https://github.com/dat-ecosystem/dat-ecosystem/commit/5e14ee5ddc77ddbc654a4c31015f3c5ec6f6b19c#diff-787aadfd200d8db1028fd79d1ea665f7c7262457cbcc8dee726b301fe2c73167)

---

## worklog 

[worklog-167](https://youtu.be/eTp45j_Dlqk)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- update button_v0.0.7
   - update - select_button
   - update - sm_icon_button
   - create - day_button - `1h`
   - create - year_button - `1h`
   - create - worklog comment, and task- `15min`
   - `@output` 📦 [button_v0.0.8](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-b360ac18a2e2bc691a494c8e91d3c137e1e2195053849b2bdacbb34cd4bab9c4)

---

## worklog 

[worklog-166](https://youtu.be/xVAqdOusnGc)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.3`

- update button_v0.0.8 - `1h`
   - create tab_button
   - create - worklog comment, and task- `11min`
   - `@output` 📦 [button_v0.0.9](https://github.com/dat-ecosystem/dat-ecosystem/commit/cb1afc5e39f1507d9b9c4ead6249ffa55ea93d21#diff-e4dfbf7e0c2ecad289c731c77ad9ee66cd814fcfd6e8532932b3a25cd2be62cd)

---

## worklog 

[worklog-167](https://youtu.be/eTp45j_Dlqk)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.17`

- update button_v0.0.9 - `22min`
   - update day_button
   - update select_button
   - update year_button
   - create - worklog comment, and task- `8min`
   - `@output` 📦 [button_v0.0.10](https://github.com/Mehrabbruno/dat-ecosystem/commit/a86532327864adc0c34a22ab3c77e32246d83c41#diff-b360ac18a2e2bc691a494c8e91d3c137e1e2195053849b2bdacbb34cd4bab9c4)

---

## worklog 

[worklog-169](https://youtu.be/qrFhSCVUESM)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.20`

- update button_v0.0.14 
   - updated icon button - `10min`
   - `@output` 📦 [button_v0.0.15](https://github.com/Mehrabbruno/dat-ecosystem/commit/dcde5b75a1678864dee5081cddeea72f911246e3#diff-63153c41ced441033124c1585c007fee67b2ec3485396288f6ab181c06b2865d)

---

- update button_v0.0.15
   - updated logo button - `5min`
   - updated select button - `32min`
   - updated sm-text-button - `10min`
   - create and update tasks - `11min`
   - `@output` 📦 [button_v0.0.16](https://github.com/Mehrabbruno/dat-ecosystem/commit/881a26bada669a019653f538481f934b8b02d598#diff-e25524e3d7115f2c34d590b72056a8bebaa951048e5273cba10446c086ad0399)

---

## worklog 

[worklog-188](https://youtu.be/K7D_jrcDjIc)

---

## feedback
  
---

## proposal
