### ISSUE TITLE
code - app timeline mini component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#10]
#3

## `todo`

- [x] code - app timeline mini
   - `@input` 📦 [`timeline_card_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-931aab9f12c22b4ea8c8350eb4d25d1b3338f7d191b851edc3f3bd548c8aef8f) from #9 
   - `@input` 📦 [`window_bar_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add timeline card 
   - [x] add window bar
   - [x] make the timeline responsive
   - `@output` 📦 [app_timeline_mini_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-c97d768044744ef7e2ee9da98baa98e7cafb0e1f7df63ef514905af1088959c8) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.03`

- code - app timeline mini - `50min`
   - add timeline card
   - add window bar
   - make the timeline responsive
   - create - worklog comment, and task- `13min`
   - `@output` 📦 [`app_timeline_mini_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-c97d768044744ef7e2ee9da98baa98e7cafb0e1f7df63ef514905af1088959c8)

---

## worklog 

[worklog-149](https://youtu.be/l0yaPv_6oLI)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.08`**


## regarding themes

...and i noticed now in many places you wrote `<style> ${get_theme} </style>` instead of `<style> ${get_theme()} </style>`

Now, at the moment, it anyway makes not much sense, because the point is to differentiate between individual styling of an individual component instance compared to a style that affects all component instances of a certain type, e.g.:

a specific component should look different than all the components for example.

We achieve the overall component styling with
```js

const sheet = new CSSStyleSheet
const theme = get_theme()
sheet.replaceSync(theme)

// and later for each instance we write

shadow.adoptedStyleSheets = [ sheet ]
```
That gives all component instances a shared styling

On the other hand, we can use the `props` or how i usually write `opts` or a protocol message to pass in custom theme/style to a specific component instance and that style will appear only for that particular component instance and not for all of them.
It can be applied via:

   shadow.innerHTML = `
        <div class="main_wrapper">
            <div class="timeline_wrapper">
            </div>
        </div>
        <style> ${custom_styling} </style>
    `
```

**BUT** to pass in both cases the absolute identical `get_theme()` is redundant, so if you don't plan to ever pass custom styling to a particular button instance, then you can simplify your html markup to just 

```js
   shadow.innerHTML = `
      <div class="main_wrapper">
        <div class="timeline_wrapper"></div>
      </div>
    `
```


yeah otherwise, feedback repeats, as in other issues, improve the following:
```js
    // Listening to toggle event 
    const listen = (props) =>{
        const {active_state} = props
        ;(active_state==='active')?el.style.display = 'none':''
    }

    // Adding Applicatin window Bar
    const view_more_btn = sm_text_button({text:'View more (12)'})
    const cover_window = window_bar({
        name:'TIMELINE', 
        src: icon_folder,
        action_buttons: [view_more_btn]
    }, listen)
 ```
 The message format always needs to be `{ head, refs, type, data, meta }`
 If you could get closer to standardjs + snake_case would be great.
 And params should always be `JSON.stringify`able, other than the protocol.
 so:
 ```js

  // Adding Applicatin window Bar
  const cover_window = window_bar({
      name:'TIMELINE', 
      src: icon_folder,
      action_buttons: ['View more (12)']
  }, protocol)
  
  // ...
  return el
  function windowbar_protocol (send) {
    return function listen (message) {
      const { data: props } = message
      const { active_state } = props
      active_stat e=== 'active' ? el.style.display = 'none' : ''
    }
  }
```

and finally, `cards_data` should be passed as message props or protocol message and not hard coded inside a re-usable component.

And finally the following can be simplified
```js
    const timeline_cards = cards_data.map((card_data) => timeline_card(card_data))
    timeline_cards.forEach((card) => {
        timeline_wrapper.append(card)
    })
```
to just
```js
  timeline_wrapper.append(...cards_data.map(timeline_card))
```
it means exactly the same and if we don't make use of it, then vanillajs apps become much more verbose than they need to be :-)

lastly, even though it is concise, it is not so obviously readable as if it was explicitly marked in the html template, so
```js
    shadow.innerHTML = `
        <div class="main_wrapper">
            <div class="timeline_wrapper">
            </div>
        </div>
        <style> ${get_theme} </style>
    `
    
    // ....
    
   
    shadow.prepend(cover_window)
 ```
 would be more obvious if it was
 ```js
  shadow.innerHTML = `
    <cover_window></cover_window>
    <div class="main_wrapper">
      <div class="timeline_wrapper"></div>
    </div>
    <style> ${get_theme()} </style>
  `
  // ...
  shadow.querySelector('cover_window').replaceWith(cover_window)
```

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.11`

- update app_timeline_mini_v0.0.1 - `15min`
   - fix the issue on chrome
   - update background-pattern - `4min`
   - `@output` 📦 [app_timeline_mini_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/6ff16cf64769d872a36d94959642dd10236c71bd#diff-0c394a5caf6bd14ce7b6642c6e12d87a729b33dbd7de84a2e11c16785f05deff)

---

## worklog 

[worklog-181](https://youtu.be/ShRemmsZ1y0)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.08`

- update app_timeline_mini_v0.0.2 
   - code - navigation protocol - `15min`
   - create and update tasks - `13min`
   - `@output` 📦[`app_timeline_mini_v0.0.2 `](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-c97d768044744ef7e2ee9da98baa98e7cafb0e1f7df63ef514905af1088959c8)

---

## worklog 

[worklog-186](https://youtu.be/MOQkD8p4XK4)

---

## feedback
  
---

## proposal

**Comment by ninabreznik** [comment]
Awesome. I noticed one thing in filtering. If I select to show only `projects` and then click year 2016 I would expect to see only entries with the `projects` tag from 2016, not all of them. What do you think?
