### ISSUE TITLE
Update - app_cover Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#10]
## `todo`

- [x] Update app_cover_v0.1.0
  - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #4 
  - [x] Remove tell me more button and make content visible
  - `@output` :package: [`app_cover_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/0309d633686016ce192ec0ceba3142668a2dbbeb) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/9#issuecomment-1913426389)

---

- [ ] Finalize app_cover_v0.1.?
   - [ ] code app_cover
   - `@output` :package: `app_cover_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update app_cover_v0.1.0
  - Removed tell me more button and make content visible - `7min`
  - Created and logged tasks - `12min`
  - `@output` :package: [`app_cover_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/0309d633686016ce192ec0ceba3142668a2dbbeb)

---

### worklog

[worklog-196](https://youtu.be/Y69DqGC5wo0)

---

### feedback

---

### proposals
