### ISSUE TITLE
code - project card component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#11]
#3

## `todo`

- [x] code - project_card_v0.0.1
   - `@input` 📦 [buttons_v0.0.4](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-a86de8010d972be7365507d0a6c452bcbbd536fef72ad4a3ec6ce8c84a8fb0bc) from [issue#71](https://github.com/dat-ecosystem/organization/issues/71)
   - [x] add social icon buttons
   - [x] add project logo
   - [x] add project info
   - `@output` 📦 [project_card_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-931aab9f12c22b4ea8c8350eb4d25d1b3338f7d191b851edc3f3bd548c8aef8f) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.03`

- code - project_card_v0.0.1 - `1h`
   - add social icon buttons
   - add project logo
   - add project info
   - updated the previous committed code - `19min`
   - create - worklog comment, and task- `9min`
   - `@output` 📦 [`project_card_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-931aab9f12c22b4ea8c8350eb4d25d1b3338f7d191b851edc3f3bd548c8aef8f)

---

## worklog 

[worklog-149](https://youtu.be/l0yaPv_6oLI)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.08`**
Fine, again, some code feedback.
First, this time you even have some unnecessary semicolons, hope it wont get worse, but otherwise:
```js
    shadow.innerHTML = `
        <div class="project_card">
            <div class="icon_wrapper">
                <div class="project_title">
                    ${props.project}
                </div>
                <div class="socials_wrapper"></div>
            </div>
            <div class="content_wrapper">
                <div class="desc"> ${props.desc}</div>
            </div>
            <div class="tags_wrapper">
                ${props.tags.map((tag) => `<div class="tag">${tag}</div>`).join('')}
            </div>
        </div>
        <style>${get_theme}</style>
    `
    // Adding Project Logo
    const project_title = shadow.querySelector('.project_title');

    const project_logo = document.createElement('img')
    project_logo.src = props.project_logo
    project_title.prepend(project_logo)

    // Adding Socials
    const socials_wrapper = shadow.querySelector('.socials_wrapper');
    const social_link = props.socials.map((social) => sm_icon_button({src:social}));
    social_link.forEach((social) => {
        socials_wrapper.append(social);
    });
```
can be simplified to
```js
shadow.innerHTML = `
  <div class="project_card">
    <div class="icon_wrapper">
      <div class="project_title">
        ${props.project}
        <img src="${props.project_logo}">
      </div>
      <div class="socials_wrapper">
        <socials></socials>
      </div>
    </div>
    <div class="content_wrapper">
      <div class="desc"> ${props.desc}</div>
    </div>
    <div class="tags_wrapper">
      ${props.tags.map((tag) => `<div class="tag">${tag}</div>`).join('')}
    </div>
  </div>
  <style>${get_theme}</style>
`
const socials = props.socials.map(social => sm_icon_button({ src: social })
shadow.querySelector('socials').replaceWith(...socials))
```

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.27`

- code - project_card_v0.0.2 - `56min`
   - update the project_content with updated data
   - update project social links condition
   - fix project card height
   - create - worklog comment, and task- `6min`
   - `@output` 📦 [project_card_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/2dd31a45fbb23d641741e0b97e0911f1799e9f0b#diff-3e72dd032a73f76f09168012f36d14517a244559e27a801472ae9485bf72eebe)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback

---

## proposal
