### ISSUE TITLE
Update - app_footer Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#11]
## `todo`

- [x] Update app_footer_v0.1.0
   - `@input` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from #3 
   - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #4
   - [x] update the app_footer component
   - `@output` :package:  [`app_footer_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-footer/app-footer.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/10#issuecomment-1913429022)

---

- [ ] Finalize app_footer_v0.1.?
   - [ ] code app_footer
   - `@output` :package: `app_footer_v0.1.?` from `comment`
   - next #11

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update app_footer_v0.1.0
   - update the app_footer component
   - `@output` :package:  [`app_footer_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-footer/app-footer.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
