### ISSUE TITLE
code - app projects mini component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#12]
#3

## `todo`

- [x] code - app_projects_mini
   - `@input` 📦 [`project_card_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-5bb1f4606e6d9769527ac8525d7cf2499457e6c4d7d3dc91d17717d85ae581bf) from #11 
   - `@input` 📦 [`window_bar_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add project card 
   - [x] add window bar
   - [x] make the project mini responsive
   - `@output` 📦 [`app_projects_mini_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-7b61c96bd9dc4a6eec32251bea98655d9c2077634c1ec56d43feb43cc0101bf9) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.03`

- code - app_projects_mini  - `2min`
   - add project card
   - add window bar
   - make the project mini responsive
   - push all the updates - `9min`
   - create - worklog comment, and task- `9min`
   - `@output` 📦 [`app_projects_mini_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-7b61c96bd9dc4a6eec32251bea98655d9c2077634c1ec56d43feb43cc0101bf9)

---

## worklog 

[worklog-149](https://youtu.be/l0yaPv_6oLI)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.08`**


problem: responsive toggle
=> should not overlay content (e.g. cards), but rather move cards down imho.
=> cards can move back up when overlay gets "de toggled" :-)

Otherwise, in code, the `"cardsData"` should be passed in from the outside as params,
maybe as a protocol message, to update things at runtime, maybe trggered by the user or whatever, but it shouldn't be hard coded in the component.

Anyway, I assume that's anyway just the case for now while we code things together.

But one more coding trick, you can do:
```js
    const project_cards = cardsData.map((card_data) => project_card(card_data))
    project_cards.forEach((card) => {
        project_wrapper.append(card)
    })
```
can be replaced with:
```js
    project_wrapper.append(...cardsData.map(project_card))
```

## otherwise, as said elsewhere already
1. its not standardjs + snake_case, e.g. 2 space indent, function () {} instead of function(){
2. protocol listen function message needs to be `{ head, refs, type, data, meta }`
3. no passing of non-serializable data to sub components, other than protocol, e.g.
```js
    // Adding Applicatin window Bar
    const view_more_btn = sm_text_button({text:'View more (12)'})
    const cover_window = window_bar({
        name:'OUR PROJECTS', 
        src: icon_folder,
        action_buttons: [view_more_btn]
    }, listen)
```
should become
```js
    // Adding Applicatin window Bar
    const cover_window = window_bar({
        name:'OUR PROJECTS', 
        src: icon_folder,
        action_buttons: ['View more (12)']
    }, listen)
```
But again, more than that, the protocol passed is not just a `listen` function.
That would allow only one-way-communication, but we might want to send "theme update" messages to the button inside the window_bar, that's why it should actually be:
```js
    // Adding Applicatin window Bar
    const cover_window = window_bar({
        name:'OUR PROJECTS', 
        src: icon_folder,
        action_buttons: ['View more (12)']
    }, protocol)
```
where protocol looks more like your listen funciton, but wrapped, thus:
```js
function windowbar_protocol (send) {
  return function listen (message) {
    const { data: props } = message
    const { active_state } = props
    active_state === 'active') ? el.style.display = 'none' : ''
  }
}
```

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.11`

- update - app_projects_mini_v0.0.1 - `15min`
   - fix the issue on chrome
   - update background-pattern - `5min`
   - `@output` 📦 [app_projects_mini_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/6ff16cf64769d872a36d94959642dd10236c71bd#diff-7f0494d5ae1977601c41ebbec2e74fefcf4cfe687e69812716a8dca2c806004b)

---

## worklog 

[worklog-181](https://youtu.be/ShRemmsZ1y0)

---

## feedback

---

## proposal

**Comment by ninabreznik** [comment]
There is a visual bug when switching between dark and light theme (github logo)
[
![projects-github logo](https://github.com/dat-ecosystem/dat-ecosystem/assets/1076427/57e57d5d-17ad-4c56-867f-7d3641f82419)
](url)
