### ISSUE TITLE
Update - home_page Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#12]
## `todo`

- [x] Update home_page_v0.1.0
   - `@input` :package: [`app_about_us`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-about-us/app-about-us.js) from #5 
   - `@input` :package: [`app_project_mini`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-projects-mini/app-projects-mini.js) from #6 
   - `@input` :package: [`app_timeline_mini`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-timeline-mini/app-timeline-mini.js) from #9 
   - `@input` :package: [`app_cover`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-cover/app-cover.js) from #10 
   - `@input` :package: [`app_footer`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-footer/app-footer.js) from #11 
   - [x] on mobile - fix home_page bugs
   - `@output` :package: [`home_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/a6a4dabb4d9b18ccf895cc979b1bcc3a8bc3f97f) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/11#issuecomment-1913430940)

---

- [ ] Finalize home_page_v0.1.?
   - [ ] code home_page
   - `@output` :package: `home_page_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- [x] Update home_page_v0.1.0
   - [x] on mobile - fix home_page bugs - `26min`
   - [x] Created and logged tasks - `15min`
   - `@output` :package: [`home_page_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/a6a4dabb4d9b18ccf895cc979b1bcc3a8bc3f97f) 

---

### worklog

[worklog-196](https://youtu.be/Y69DqGC5wo0)

---

### feedback

---

### proposals
