### ISSUE TITLE
code - app about us component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#13]
#3

## `todo`

- [x] code - app_about_us
   - `@input` 📦 [`window_bar_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add robot character img
   - [x] add app title
   - [x] add app desc
   - `@output` 📦 [`app_about_us_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-f49b6278570268a9809314bb24f99b9805fbf373a827091f9ced8dde4e6fd31d) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.03`

- code - app_about_us - `1h22min`
   - add robot character img
   - add app title
   - add app desc
   - create - worklog comment, and task- `9min`
   - `@output` 📦 [`app_about_us_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-f49b6278570268a9809314bb24f99b9805fbf373a827091f9ced8dde4e6fd31d)

---

## worklog 

[worklog-149](https://youtu.be/l0yaPv_6oLI)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.08`**

looks great. maybe if there is room to scale it as big as possible without cutting things off to maximize the space in the center and then use the space in the center to make the tree as big as possible, that would be great, otherwise perfect.

## regarding code
again, similar to what i said already.
1. it's not yet standardjs + snake_case
2. you can extend your template to use `<img src="${image_name}`>` to reduce the extra code lines later on
3. **IMPORTANT** every message needs to look like `{head, refs, type, data, meta}`, thus your message with props need to at least look like this
```js
const listen = message => {
  const { data: props } = message
  const { active_state } = props
  active_state === 'active' ? el.style.display = 'none' : ''
}
```
This would support the message standard and it is now also reflecting proper standardjs :-)

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.06`

- update app_about_us_v0.0.1 - `15min`
   - code protocols
   - create - worklog comment, and task- `6min`
   - `@output` 📦 [app_about_us_v0.0.2](https://github.com/dat-ecosystem/dat-ecosystem/commit/96958e3b14e4f2745fd4c7e558a1b70f768678b7#diff-7122e6c373cecf543f152647a24b8efe37b69d16041a9952ff94fa9b2d680b26)
---

## worklog 

[worklog-161](https://youtu.be/ebYxRNGjfwM)
[worklog-162](https://youtu.be/6Eexd0g2U3o)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.08`

- update - app_about_us_v0.0.2
   - code - navigation protocol - `28min`
   - create and update tasks - `8min`
   - `@output` 📦[`app_about_us_v0.0.2`](https://github.com/Mehrabbruno/dat-ecosystem/commit/70af80a757e36e1d3032445c447e293cdb6ba696#diff-a56ba6f591139a2eeecf814eaf9f43a696bcb1792753e0b6e7e25b31dea64284)

---

## worklog 

[worklog-186](https://youtu.be/MOQkD8p4XK4)

---

## feedback
  
---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.20`

- update - app_about_us_v0.0.3
   - update about us content - `5min`
   - create and update tasks - `11min`
   - recorded worklog - `10min`
   - `@output` 📦[`app_about_us_v0.0.4`](https://github.com/Mehrabbruno/dat-ecosystem/commit/dcde5b75a1678864dee5081cddeea72f911246e3#diff-a56ba6f591139a2eeecf814eaf9f43a696bcb1792753e0b6e7e25b31dea64284)

---

## worklog 

[worklog-188](https://youtu.be/K7D_jrcDjIc)

---

## feedback
  
---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.28`

- update - app_about_us_v0.0.5
   - update the document link to project page - `20min`
   - create and update tasks - `15min`
   - recorded worklog - `12min`
   - `@output` 📦 [app_about_us_v0.0.6](https://github.com/Mehrabbruno/dat-ecosystem/commit/53f31a67cd8c015d59f4d1cd80eff76d57a6451d#diff-a56ba6f591139a2eeecf814eaf9f43a696bcb1792753e0b6e7e25b31dea64284)

---

## worklog 

[worklog-190](https://youtu.be/g8-NA3ogczk)

---

## feedback
  
---

## proposal
