### ISSUE TITLE
code - app footer component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#14]
#3

## `todo`

- [x] code - app_footer
   - `@input` 📦 [`window_bar_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add robot character img
   - [x] add app title
   - [x] add app desc
   - `@output` 📦 [`app_footer_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-c982fcf30c2f124830d362b24736c7268cd0dc3c6f0e6488858127516433ac35) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.03`

- code - app_footer - `1h37min`
   - add robot character img
   - add pattern img
   - add footer into and button
   - create - worklog comment, and task- `9min`
   - `@output` 📦 [`app_footer_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-c982fcf30c2f124830d362b24736c7268cd0dc3c6f0e6488858127516433ac35)

---

## worklog 

[worklog-149](https://youtu.be/l0yaPv_6oLI)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.08`**


"footer.pdf" is missing the "pdf program icon" in the left corner before name
you decided to leave whitespace and the robot in the footer is alone
if the hexagons work next to the robot on small screen responsiveness, cool.

## regarding code
Problem with `theme`, a theme must either be provided in `demo.js` to the entire app and the components receive it as protocol messages (e.g. for theme updates at runtime) or maybe as `opts` form the parent component.
If there is a "default theme", it needs to be co-located inside each components folder.

So `const my_theme = require('my_theme')` where `my_theme` is hard coded but a distinct component used by many does not work well.

Think of it like this - we will in the near future try to re-use components when we implement wizardamigos and when we implement datdot, which have totally different theme requirements, so it would be wasteful to pull in a random theme that was just used once in a particular project.
theme needs to be passed as parameter and protocol message for updates.
a component who has some invariants, e.g. a "logo component" where we actually hard code a specific color or image into the component.
Another example would be to code a "traffic light", so you might just hard code the red/green colors, because when you don't use those colors it hardly gets recognized as a "traffic light".

---

Next I think some things could probably be coded directly into the HTML markup, e.g.:

```js
// Adding Robot Image
const robot_image_wrapper = shadow.querySelector('.robot_img_2')
const robot_image = document.createElement('img')
robot_image.src = img_robot_2
robot_image_wrapper.append(robot_image)
    
// Adding Pattern Image
const pattern_image_wrapper = shadow.querySelector('.pattern_img')
const pattern_image = document.createElement('img')
pattern_image.src = pattern_img_1
pattern_image_wrapper.append(pattern_image)
```
that code can probably be removed and instead you just update your template snippet
```js
shadow.innerHTML = `
    <div class="main_wrapper">
        <div class="footer_wrapper">
            <div class="robot_img_2"><img src="${img_robot_2}"></div>
            <div class="footer_info_wrapper">
                <div class="title"> INTERESTED IN JOINING DAT ECOSYSTEM CHAT NETWORKING? </div>
                <div class="desc"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae porta aliquet sit amet ornare sagittis, ultricies sed. Viverra sit felis ullamcorper pharetra mattis amet, vel. </div>
            </div>
           <apply_button></apply_button>
        </div>
        <div class="pattern_img"><img src="${pattern_img_1}"></div>
    </div>
    <style> ${get_theme} </style>
`

// the following is the pattern we usually use, but what you do is more or less the same
// so you can also keep your three liner :-)
const join_programe = sm_text_button({text:'JOIN OUR GROWTH PROGRAME'})
shadow.querySelector('apply_button').replaceWith(join_programe)
```

Otherwise, the code looks great :-)
your formatting is still not standardjs + snake_case thought, but i can live with it.
standardjs would be `2 space indentation` and ` get_theme () {` instead of `get_theme(){`
and also instead of `el.attachShadow ( { mode : 'closed' } )` it would be
`el.attachShadow({ mode : 'closed' })` and `const listen = (props) => {` instead of `const listen = (props) =>{` or in case of one parameter you can even do `const listen = props => {` and a few other details, but overall the code looks decent.

**Comment by ninabreznik** [comment]
Since we haven't managed to make the whole DAt garden post growth program, we should for now adjust the footer to say:

Interested in learning more about the Dat Ecosystem?
Join our [chat](https://discord.gg/egsvGc9TkQ) and discuss tech, society, funding and your project development with the community. But you can also subscribe to the newsletter updates!

Join the newsletter

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.20`

- update - app_footer_v0.0.1 
   - updated content and hyperlink - `5min`
   - create and update tasks - `8min`
   - `@output` 📦 [app_footer_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/dcde5b75a1678864dee5081cddeea72f911246e3#diff-8c63c05882c4b725eb0247933a5913ab4b0477844255ef62471c00663f7f45c5)

---

## worklog 

[worklog-188](https://youtu.be/K7D_jrcDjIc)

---

## feedback
  
---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.28`

- update - app_footer_v0.0.2 - `13min`
   - update the content text
   - update the link to mailbox
   - @output 📦 [app_footer_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/53f31a67cd8c015d59f4d1cd80eff76d57a6451d#diff-8c63c05882c4b725eb0247933a5913ab4b0477844255ef62471c00663f7f45c5)

---

- update - app_footer_v0.0.3
   - create a filled image of robot - `23min`
   - update the robot fill in the footer - `18min`
   - create and update tasks - `9min`
   - `@output` 📦 [app_footer_v0.0.4](https://github.com/Mehrabbruno/dat-ecosystem/commit/6c6cb47818beae36c6c9979e54ee0eb68a99d7cb)

---

## worklog 

[worklog-190](https://youtu.be/g8-NA3ogczk)

---

## feedback
  
---

## proposal
