### ISSUE TITLE
Update - search_input Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#14]
## `todo`

- [x] Update search_input_v0.1.0
   - [x] update the search_input component
   - `@output` :package: [`search_input_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/search-input/search-input.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/13#issuecomment-1913504054)

---

- [ ] Finalize search_input_v0.1.?
   - [ ] code the search_input
   - `@output` :package: `search_input_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update search_input_v0.1.0
   - update the search_input component
   - `@output` :package: [`search_input_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/search-input/search-input.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
