### ISSUE TITLE
code - filter components

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#16]
#4

## `todo`

- [x] code - filter component
   - `@input` 📦 [`buttons_v0.0.5`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/a56d67719e31e276fd606660c518a0b21b1896e8#diff-787aadfd200d8db1028fd79d1ea665f7c7262457cbcc8dee726b301fe2c73167) from #1 
   - `@input` 📦 [`search_input_v0.0.1`]() from #17 
   - [x] add select_button for Status
   - [x] add select_button for tags
   - [x] add search input
   - `@output` 📦 [filter component_v0.0.1]() from [comment]()

---

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.10`

- code - search_input_v0.0.1 - `50min`
   - create comment, and task - `11min`
   - create worklog - `11min`
   - `@output` 📦 [`search_input_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/e2022be9464305c7655a826debcef9a6882ba554#diff-2285f743f52902c1d370405ae1b051f8600e376a921d42691f47ceb9d15b87f6)

---

## worklog 

[worklog-153](https://youtu.be/mPJLgQG1JkI)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.11`**

```js
    const el = document.createElement('div')
    const shadow = el.attachShadow( { mode:`closed` } )
    shadow.innerHTML = `
        <div class="filter_wrapper">
            <div class="project_filter"></div>
        </div>
        <style> ${get_theme} </style>
    `
```

related to other feedback, it is either `get_theme()` or nothing at all,
because `shadow.adoptedStyleSheets = [sheet]` already covers that

otherwise, whatever other generic feedback applied to other feedback comment, e.g. standardjs or certain ways of stucturing the component

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.06`

- update - project_filter_v0.0.1
   - code protocols for filters using select_button and search_input - `1h10min`
   - create - worklog comment, and task- `14min`
   - `@output` 📦 [`project_filter_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/commit/b64ef92f3e2d5ef9343e4be88ac5257f3dd756f2#diff-cc750cb241b9b25ad88d21128703911ec4ccc893e59d29d60f085821491cbe1c)

---

## worklog 

[worklog-163](https://youtu.be/m5hS6hZUl6A)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- update - project_filter_v0.0.2 - `10min`
   - update filter's passed data
   - create - worklog comment, and task- `14min`
   - `@output` 📦 [project_filter_v0.0.3](https://github.com/dat-ecosystem/dat-ecosystem/commit/5e14ee5ddc77ddbc654a4c31015f3c5ec6f6b19c#diff-cc750cb241b9b25ad88d21128703911ec4ccc893e59d29d60f085821491cbe1c)
---

## worklog 

[worklog-167](https://youtu.be/eTp45j_Dlqk)

---

## feedback

---

## proposal
