### ISSUE TITLE
code - search_input

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#17]
#4

## `todo`

- [x] code - search_input_v0.0.1
   - [x] create input field
   - [x] add search icon
   - `@output` 📦 [`search_input_v0.0.1`]() from [comment]()

---

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.10`

- code - search_input_v0.0.1 - `28min`
   - create comment, and task - `11min`
   - create worklog - `11min`
   - `@output` 📦 [`search_input_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/e2022be9464305c7655a826debcef9a6882ba554#diff-2285f743f52902c1d370405ae1b051f8600e376a921d42691f47ceb9d15b87f6)

---

## worklog 

[worklog-153](https://youtu.be/mPJLgQG1JkI)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.11`**

```js
    const el = document.createElement('div')
    // el.classList.add('input_wrapper')
    const shadow = el.attachShadow( { mode:`closed` } )
    shadow.innerHTML = `
        <div class="filter_wrapper">
            <div class="project_filter"></div>
        </div>
        <style> ${get_theme} </style>
    `
```

related to other feedback, it is either `get_theme()` or nothing at all,
because `shadow.adoptedStyleSheets = [sheet]` already covers that

otherwise, whatever other generic feedback applied to other feedback comment, e.g. standardjs or certain ways of stucturing the component

---

## regarding `// el.classList.add('input_wrapper')`

you can always use the css pseudoclass
```css
:host {
 color: pink;
}
```
to target the `el` host element of your shadow, so it doesn't need a special class

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.06`

- update - search_input_v0.0.1
   - code input protocol - `1h3min`
   - create - worklog comment, and task- `11min`
   - `@output` 📦 [`search_input_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/commit/b64ef92f3e2d5ef9343e4be88ac5257f3dd756f2#diff-2285f743f52902c1d370405ae1b051f8600e376a921d42691f47ceb9d15b87f6)

---

## worklog 

[worklog-163](https://youtu.be/m5hS6hZUl6A)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.30`

- update search_input_v0.0.2 - `10min`
   - update function_name and passed data
   - create - worklog comment, and task- `8min`
   - @output 📦 [search_input_v0.0.3](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-2285f743f52902c1d370405ae1b051f8600e376a921d42691f47ceb9d15b87f6)

---

## worklog 

[worklog-165](https://youtu.be/CG_CPiDhaaU)

---

## feedback

---

## proposal
