### ISSUE TITLE
code - scrollbar component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#18]
#4

## `todo`

- [x] code - custom scrollbar component
   - [x] read code of simple-scrollbar
   - [x] code a custom scrollbar component
   - [x] code protocol for scrollbar component
   - [x] add it to app_timeline_mini component for test
   - `@output` 📦 [` scrollbar_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/8174840620e13a621a836c822397acb11d2bf8d9#diff-88b05de60fd01eba66b7bd67daf3fb093e5f932b3e7ae68cee7f9a93a1168289) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.23`

- code - custom scrollbar component
   - read code of simple-scrollbar - `20min`
   - code a custom scrollbar component  - `4h`
   - code protocol for scrollbar component -`1h`
   - add it to app_timeline_mini component for test
   - create - worklog comment, and task- `13min`
   - `@output` 📦 [`app_timeline_mini_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-c97d768044744ef7e2ee9da98baa98e7cafb0e1f7df63ef514905af1088959c8)

---

## worklog 

[worklog-159](https://youtu.be/mnuVNbMGUFw)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.06`

- update scrollbar_v0.0.1 
   - update the scrollbar protocols - `58min`
   - update the scrollbar svgs - `10min`
   - create - worklog comment, and task- `16min`
   - `@output` 📦 [`scrollbar_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/commit/b64ef92f3e2d5ef9343e4be88ac5257f3dd756f2#diff-88b05de60fd01eba66b7bd67daf3fb093e5f932b3e7ae68cee7f9a93a1168289)

---

## worklog 

[worklog-163](https://youtu.be/m5hS6hZUl6A)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- update scrollbar_v0.0.2 - `36min`
   - update the scrollbar observers
   - create - worklog comment, and task- `12min`
   - `@output` 📦 [scrollbar_v0.0.3](https://github.com/dat-ecosystem/dat-ecosystem/commit/5e14ee5ddc77ddbc654a4c31015f3c5ec6f6b19c#diff-88b05de60fd01eba66b7bd67daf3fb093e5f932b3e7ae68cee7f9a93a1168289) 

---

## worklog 

[worklog-167](https://youtu.be/eTp45j_Dlqk)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- update scrollbar_v0.0.3 - `29min`
   - update the scrollbar observers
   - update arrow-icons
   - create - worklog comment, and task- `13min`
   - `@output` 📦 [scrollbar_v0.0.4](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-88b05de60fd01eba66b7bd67daf3fb093e5f932b3e7ae68cee7f9a93a1168289)

---

## worklog 

[worklog-165](https://youtu.be/CG_CPiDhaaU)

---

## feedback

---

## proposal
