### ISSUE TITLE
code - app project component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#19]
#4 

## `todo`

- [x] code app_projects component
   - `@input` 📦 [`project_filter_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/commit/b64ef92f3e2d5ef9343e4be88ac5257f3dd756f2#diff-cc750cb241b9b25ad88d21128703911ec4ccc893e59d29d60f085821491cbe1c) from #16
   - `@input` 📦 [`project_card_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-5bb1f4606e6d9769527ac8525d7cf2499457e6c4d7d3dc91d17717d85ae581bf) from #11 
   - `@input` 📦 [`scrollbar_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/commit/b64ef92f3e2d5ef9343e4be88ac5257f3dd756f2#diff-88b05de60fd01eba66b7bd67daf3fb093e5f932b3e7ae68cee7f9a93a1168289) from #18 
   - [x] add filter component into the app_projects_component
   - [x] add scrollbar component into the app_projects_component
   - `@output` 📦 [`app_projects_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/b64ef92f3e2d5ef9343e4be88ac5257f3dd756f2#diff-c85e38bb86e92df54ee6f33bb396fcd754c462eacc4b41cc803e08472065244f) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.06`

- code app_projects component
   - add filter component into the app_projects_component - `40min`
   - add scrollbar component into the app_projects_component - `34min`
   - fix all the bug/issues - `38min`
   - create - worklog comment, and task- `13min`
   - `@output` 📦 [`project_filter_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/commit/b64ef92f3e2d5ef9343e4be88ac5257f3dd756f2#diff-cc750cb241b9b25ad88d21128703911ec4ccc893e59d29d60f085821491cbe1c)

---

## worklog 

[worklog-163](https://youtu.be/m5hS6hZUl6A)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- update app_projects_v0.0.1 - `1h12min`
   - add tags data
   - code protocol for tag filter
   - code protocol for project status filter
   - code protocol for search filter
   - create - worklog comment, and task- `15min`
   - `@output` 📦 [app_projects_v0.0.2](https://github.com/dat-ecosystem/dat-ecosystem/commit/5e14ee5ddc77ddbc654a4c31015f3c5ec6f6b19c#diff-c85e38bb86e92df54ee6f33bb396fcd754c462eacc4b41cc803e08472065244f)

---

## worklog 

[worklog-167](https://youtu.be/eTp45j_Dlqk)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- update app_projects_v0.0.2 - `27min`
   - update the protocol to fit scrollbar
   - create - worklog comment, and task- `12min`
   - `@output` 📦 [app_projects_v0.0.3](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-c85e38bb86e92df54ee6f33bb396fcd754c462eacc4b41cc803e08472065244f)
---

## worklog 

[worklog-165](https://youtu.be/CG_CPiDhaaU)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.27`

- update app_projects_v0.0.4
   - get project contents - `53min`
   - update app_project with contents data - `10min`
   - create - worklog comment, and task- `11min`
   - `@output` 📦 [app_projects_v0.0.4](https://github.com/Mehrabbruno/dat-ecosystem/commit/cf90532a3d26518bb17fe1bde3420e061e6483b6#diff-a4d62a81346d1b90651e9c3bd76b5f4ad920d33521574ae659ce5fd5e4c44248)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback

---

## proposal
