### ISSUE TITLE
code - navbar components

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#2]
## `todo`

- [x] code - navbar component
   - `@input` 📦 [`navbar_v0.0.12`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?node-id=1529-1911&t=mOIaKkssbiRF2cWj-4) from [issue#71](https://github.com/dat-ecosystem/organization/issues/72)
   - `@input` 📦 [`button_v0.0.1`](https://github.com/Mehrabbruno/dat-ecosystem/commit/586067b43eecef85e5bb55cabbcea42bcd20ef9b) from #1 
   - [x] add all the buttons into the navbar
   - `@output` 📦 [navbar_v0.0.1](https://github.com/Mehrabbruno/dat-ecosystem/commit/83dca4ea929a440c15ddda3654b10e9f8fbb48dc) from [comment]()

---

- [x] update navbar_v0.0.1
   - `@input` 📦 [navbar_v0.0.1](https://github.com/Mehrabbruno/dat-ecosystem/commit/83dca4ea929a440c15ddda3654b10e9f8fbb48dc)
   - [x] update the navbar to be mobile first and responsive
   - `@output` 📦 [navbar_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/b4e88d1327c0c48c511a7e2928edb0059092bca7) from [comment]()

**Comment by Mehrabbruno** [comment]
### tasks - `2023.05.20`

- code - navbar component   - `1h06min`
   - add all the buttons into the navbar
   - `@output` 📦 [navbar_v0.0.1](https://github.com/Mehrabbruno/dat-ecosystem/commit/83dca4ea929a440c15ddda3654b10e9f8fbb48dc)
- update navbar_v0.0.1
   - update the navbar to be mobile first and responsive - `1h48min`
   - create and update tasks, worklog etc  - `6min`
   - `@output` 📦 [navbar_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/b4e88d1327c0c48c511a7e2928edb0059092bca7)

---

## worklog 

---

## feedback

- created navbar components
- updated navbar component to be responsive and mobile first

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.05.19`**

code looks good. i linked the issue above to its parent issue. output should be used in `page component` issue as an input and also listed in dat-website issue. the issues all need some updates, but if you accept the invite you should hopefully be able to edit the issues.

## otherwise
1. the code isn't yet in `standardjs` style (e.g. 2 spaced + `function fn_name () { }` instead of `function fn_name(){ }`
2. `require('buttons')` instead of `require('../buttons/index.js')` is why we use `/src/node_modules/buttons` as folder structure
3. per navbar instance we create, there should be just one style sheet, so it should be like:
```js
const buttons = require('buttons')

module.exports = navbar

// CSS Boiler Plat
const sheet = new CSSStyleSheet
const theme = get_theme()
sheet.replaceSync(theme)

function navbar () {
  const el = document.createElement('div')
  const shadow = el.attachShadow({ mode: 'closed' })
  
  // ...
  
}
```

**Comment by Mehrabbruno** [comment]
### tasks - `2023.05.26`

- update navbar_v0.0.3
   - update the code links - `17min`
   - read feedback - `2min`
   - code navbar toggle - `23min`
   - create and update tasks, worklog etc  - `6min`
   - adding all the icons with navbar, window_bar etc - `1h52min`
   - passing all the states to icon_button component - `41min`
   - create and update worklogs and task - `min`
   - `@output` 📦 [navbar_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/b4e88d1327c0c48c511a7e2928edb0059092bca7)

---

## worklog 

---

## feedback

- created navbar components
- updated the project structure
- added navbar toggle function
- added proper path of icon images
- pass all the icon_button states and toggle function

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.03`

- update navbar_v0.0.3 - `1h33min`
   - code theme protocol for navbar
   - create - worklog comment, and task- `10min`
   - `@output` 📦 [`navbar_v0.0.4`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-c350355782ad8dbbaf52b78e0ad161dd2952f72c07586109c4f1c597eb82b10a)

---

## worklog 

[worklog-149](https://youtu.be/l0yaPv_6oLI)
[worklog-150](https://youtu.be/BQzQEPrNpbw)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.08`**

## regarding navbar buttons
icons should be svgs, agree,makes it more flexible and themeable,lets convert

could we make the "dat ecosystem" black with green font
but all other buttons green with black font?
=> that way the hexagon leaf logo sticks out more compared to green on green

![navbar](https://imgur.com/vFEKkN5.png)

we need a "hover" color or pattern, maybe:
![hover pattern](https://imgur.com/sIdNo2t.png)
we need an "active" color or pattern, maybe:
![active pattern](https://i.imgur.com/8v3EUzA.png)

...for example, but of course with our exact pink, not some random pink :P

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.17`

- update navbar_v0.0.4
   - update theme protocol - `40min`
   - update logo button
   - create - worklog comment, and task- `19min`
   - `@output` 📦 [`navbar_v0.0.5`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/5fb131c198d634e76e5cc09bc5a653fcaecebaaf#diff-c350355782ad8dbbaf52b78e0ad161dd2952f72c07586109c4f1c597eb82b10a)

---

## worklog 

[worklog-154](https://youtu.be/g0IGPcYg5ts)
[worklog-155](https://youtu.be/7paMxUviKQQ)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.23`

- update navbar_v0.0.5 - `28min`
   - update - navbar events and responsiveness
   - create - worklog comment, and task- `18min`
   - `@output` 📦 [`navbar_v0.0.6`](https://github.com/dat-ecosystem/dat-ecosystem/commit/8ccdb236207afd849d01c9b24bf5e082efed101b#diff-c350355782ad8dbbaf52b78e0ad161dd2952f72c07586109c4f1c597eb82b10a)

---

## worklog 

[worklog-157](https://youtu.be/mvjnPYMM1cE)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.06`

- update navbar_v0.0.6
   - update navigation protocol - `2h`
   - code page toggle/navigation - `1h`
   - update svgs
   - update dropdown toggle
   - create - worklog comment, and task- `14min`
   - `@output` 📦 [`navbar_v0.0.7`](https://github.com/dat-ecosystem/dat-ecosystem/commit/9081561da793ce4c4240db22178bc2ae49a87863#diff-c350355782ad8dbbaf52b78e0ad161dd2952f72c07586109c4f1c597eb82b10a)

---

## worklog 

[worklog-160](https://youtu.be/vEjAzVv_N4U)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.11`

- update navbar_v0.0.6 - `32min`
   - updated - background pattern
   - create - worklog comment, and task - `8min`
   - `@output` 📦 [navbar_v0.0.8](https://github.com/Mehrabbruno/dat-ecosystem/commit/d0720179de6014691f2ec16d49ffe7893f7a490b#diff-1ea515a4cb7ff9cdad4089e04548813e9f7cbd296d817b41631101739bf6e869)

---

## worklog 

[worklog-181](https://youtu.be/ShRemmsZ1y0)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.08`

- update navbar_v0.0.8 
   - updated - protocol and change highlight - `25min`
   - create and update tasks - `5min`
   - `@output` 📦[`window_bar_v0.0.9`](https://github.com/Mehrabbruno/dat-ecosystem/commit/70af80a757e36e1d3032445c447e293cdb6ba696#diff-1ea515a4cb7ff9cdad4089e04548813e9f7cbd296d817b41631101739bf6e869)

---

## worklog 

[worklog-186](https://youtu.be/MOQkD8p4XK4)

---

## feedback
  
---

## proposal

**Comment by ninabreznik** [comment]
Grat job,

I am noticing we hve our main links to the socials still inactive, so let's add these too:
- they should open in a new tab
- BLOG https://blog.dat-ecosystem.org/
- Discord https://discord.com/invite/egsvGc9TkQ
- Twitter https://twitter.com/dat_ecosystem
- Github https://github.com/dat-ecosystem

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.20`

- update navbar_v0.0.9 
   - added social links - `33min`
   - create and update tasks - `5min`
   - `@output` 📦 [navbar_v0.0.10](https://github.com/Mehrabbruno/dat-ecosystem/commit/dcde5b75a1678864dee5081cddeea72f911246e3#diff-1ea515a4cb7ff9cdad4089e04548813e9f7cbd296d817b41631101739bf6e869)

---

## worklog 

[worklog-188](https://youtu.be/K7D_jrcDjIc)

---

## feedback
  
---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.29`

- update navbar_v0.0.10 - `19min`
   -  updated protocol to toggle terminal
   - create and update tasks - `5min`
   - `@output` 📦 [navbar_v0.0.11](https://github.com/Mehrabbruno/dat-ecosystem/commit/53f31a67cd8c015d59f4d1cd80eff76d57a6451d#diff-1ea515a4cb7ff9cdad4089e04548813e9f7cbd296d817b41631101739bf6e869)

---

## worklog 

[worklog-190](https://youtu.be/g8-NA3ogczk)

---

## feedback
  
---

## proposal

**Comment by Mehrabbruno** [comment]
tasks - 2024.01.13

- update navbar_v0.0.11
   - updated the active status bug on terminal command
   - `@output` 📦 [navbar_v0.0.12](https://github.com/Mehrabbruno/dat-ecosystem/commit/491898cc2aa86c6c04b1b078a49f603b86d03961#diff-1ea515a4cb7ff9cdad4089e04548813e9f7cbd296d817b41631101739bf6e869)

---

## worklog 

[worklog-191](https://youtu.be/ZNgxiVrEotw)

---

## feedback
  
---

## proposal
