### ISSUE TITLE
code - important_documents component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#25]
#4 

`###todo`

- [x] create important_documents component
   - `@input` 📦 [`window_bar_v0.0.4`](https://github.com/dat-ecosystem/dat-ecosystem/commit/96958e3b14e4f2745fd4c7e558a1b70f768678b7#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add placeholder content
    - `@output` 📦 [`important_documents_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/17df7969f721fdedf8907e1d04bec0eeb38f9558#diff-5c4341bf37930ef4baca92cb3dae003c702646e7bde3513af31f8780f4bb3168) from [comment]()
   
---

- [x] finalize button
   - `@output` :question: `button_v?.?.?` from `comment`
     - next #4
     - next #2 
     - next #5 
     - next #11
     - next #14

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- create important_documents component - `33min`
   - add placeholder content
   - create - worklog comment, and task- `10min`
   - `@output` 📦 [`important_documents_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/17df7969f721fdedf8907e1d04bec0eeb38f9558#diff-5c4341bf37930ef4baca92cb3dae003c702646e7bde3513af31f8780f4bb3168)

---

## worklog 

[worklog-164](https://youtu.be/hkCeGkhDGLg)

---

## feedback

---

## proposal

**Comment by ninabreznik** [comment]
### proposed tasks - 2023.11.12

- update important documents with this list:

- [code of conduct](https://github.com/dat-ecosystem/organization/blob/main/code-of-conduct.md)
- [code of conduct - reporting guide](https://github.com/dat-ecosystem/organization/blob/main/code-of-conduct-contact.md)
- [comm comm calls](https://github.com/dat-ecosystem/comm-comm#readme)
- [consortium meeting notes](https://github.com/dat-ecosystem/organization/tree/main/consortium/meeting%20notes)
- [visuals](https://github.com/dat-ecosystem/organization/tree/main/assets/logo%20%26%20visuals%20final)
- [organization repository](https://github.com/dat-ecosystem/organization)

**Comment by ninabreznik** [comment]
## `@TODO`

- [ ] rename `our_member.md` to members.md
- [ ] in `member.md` file rename title `our members` to `consortium members`
- [ ] in `member.md` file add another table under `consortium members` titled `alumni`
- [ ] add these names to `alumni` table:
  - Max Ogden / Dat project
  - Mathias Buus / Hypercore protocol
  - Ray (Karissa )McKelvey / Dat project
  - Paul Frazee / Beaker Browser
  - Georgiy Shibaev / Dat (Hyper) SDK
  - Andrew Osheroff / Hypercore protocol
  - Tara Vancil / Beaker Browser
  - Jim Pick / Dat Cast
  - Melanie Cebula / Dat CLI
  - Chia-liang Kao / Dat project
  - Kristina Schneider / Dat project
  - Yoshua Wuyts / datrs
  - Portia Burton / Dat project
  - Bruno Vieira / Dat project
  - Yuhong Wang / Dat project
  - Juan Batiz-Benet / Dat project
  - Finn Pauls / Dat project
  - David Clements / Hyperswarm
  - Martin Heidegger / Dat comm-comm
  - James Halliday / Dat project
  - Kira / Cabal

**Comment by ninabreznik** [comment]
## `@TODO`

- [ ] finish task from the previous comment
- [ ] replace link in `manifesto.md` from `https://hypercore-protocol.org` to `https://github.com/holepunchto/hypercore`
- [ ] open `code of conduct` link in a new tab
- [ ] manually check all the links in the projecs section (discord, github, twitter) and remove dead links or check if there's a typo or what they don't work

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.27`

- update important_documents_v0.0.1 - `12min`
   - update important_documents content and links
   - create and update tasks - `6min`
   - `@output` 📦 [`important_documents_v0.0.2`](https://github.com/Mehrabbruno/dat-ecosystem/commit/c99a40279f339ff2348e3007706bbc241a35f297#diff-756f7250945661ab80f0372ded1ba58eea7b38222ed05a17c405c8ceac9f67b4)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.29`

- update important_documents_v0.0.2 - `13min`
   - make the component open by default
   - create and update tasks - `5min`
   - `@output` 📦 [important_documents_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/53f31a67cd8c015d59f4d1cd80eff76d57a6451d#diff-756f7250945661ab80f0372ded1ba58eea7b38222ed05a17c405c8ceac9f67b4)

---

## worklog 

[worklog-190](https://youtu.be/g8-NA3ogczk)

---

## feedback
  
---

## proposal
