### ISSUE TITLE
code - mission_statement component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#26]
#4 

### `todo`

- [x] create mission_statement component
   - `@input` 📦 [`window_bar_v0.0.4`](https://github.com/dat-ecosystem/dat-ecosystem/commit/96958e3b14e4f2745fd4c7e558a1b70f768678b7#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add placeholder content
    - `@output` 📦 [`mission_statement_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/4e67329ca78d64fc1ef7d8a0eefdd9f9fe156a62#diff-ce21f129bab3334bec08adaa14b9f14193e47c2c9f58ec50281d77c41a0e036a) from [comment]()

---

- [x] update mission_statement_v0.0.1
   - `@input` 📦 [`mission_statement_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/4e67329ca78d64fc1ef7d8a0eefdd9f9fe156a62#diff-ce21f129bab3334bec08adaa14b9f14193e47c2c9f58ec50281d77c41a0e036a)
   - [x] update the pop-up to be responsive
   - `@output` 📦 [`mission_statement_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/commit/17df7969f721fdedf8907e1d04bec0eeb38f9558#diff-ce21f129bab3334bec08adaa14b9f14193e47c2c9f58ec50281d77c41a0e036a) from [comment]()
   
---

- [x] finalize mission_statement_v0.0.1
   - `@output` :question: `mission_statement_v0.0.1_v?.?.?` from `comment`
     - next #23

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- create mission_statement component - `28min`
   - add placeholder content
   - create - worklog comment, and task- `10min`
   - `@output` 📦 [`mission_statement_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/4e67329ca78d64fc1ef7d8a0eefdd9f9fe156a62#diff-ce21f129bab3334bec08adaa14b9f14193e47c2c9f58ec50281d77c41a0e036a)

---

## worklog 

[worklog-164](https://youtu.be/hkCeGkhDGLg)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- update mission_statement_v0.0.1  - `13min`
   - update the responsive with media query
   - create - worklog comment, and task- `3min`
   - `@output` 📦[`mission_statement_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/commit/17df7969f721fdedf8907e1d04bec0eeb38f9558#diff-ce21f129bab3334bec08adaa14b9f14193e47c2c9f58ec50281d77c41a0e036a)

---

## worklog 

[worklog-164](https://youtu.be/hkCeGkhDGLg)

---

## feedback

---

## proposal

**Comment by ninabreznik** [comment]
### tasks - 2023.11.16

- replace name mission statement with manifesto
- add manifesto text from `@input`: https://raw.githubusercontent.com/dat-ecosystem/organization/main/MANIFESTO.md

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.27`

- update mission_statement_v0.0.2
   - update the mission_statement title to manifesto
   - update the manifesto content with manifesto.md
   - `@output` 📦 [mission_statement_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/daf640c01cae35594402d21dc307ce96c78a6370#diff-e5084b65e8181d8f2363e752894d3b01e4019d0b812f8d4d0eae2597917838a8)

---

- update mission_statement_v0.0.3
   - fix the mission_statement broken links and content
   - `@output` 📦 [mission_statement_v0.0.4](https://github.com/Mehrabbruno/dat-ecosystem/commit/453bb1f29d768631a73b79dd2682d77b9340afcd)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback

---

## proposal
