### ISSUE TITLE
code - our_members component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#27]
#4 

### `todo`

- [x] create our_members component
   - `@input` 📦 [`window_bar_v0.0.4`](https://github.com/dat-ecosystem/dat-ecosystem/commit/96958e3b14e4f2745fd4c7e558a1b70f768678b7#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add placeholder content
    - `@output` 📦 [`our_members_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/4e67329ca78d64fc1ef7d8a0eefdd9f9fe156a62#diff-ce21f129bab3334bec08adaa14b9f14193e47c2c9f58ec50281d77c41a0e036a) from [comment](https://github.com/dat-ecosystem/dat-ecosystem/issues/26#issuecomment-1656353025)
   
---

- [x] finalize our_members_v?.?.?
   - `@output` :question: `our_members_v?.?.?` from `comment`
     - next #23

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- create our_members component - `27min`
   - add placeholder content
   - create - worklog comment, and task- `10min`
   - `@output` 📦 [`our_members_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/4e67329ca78d64fc1ef7d8a0eefdd9f9fe156a62#diff-ce21f129bab3334bec08adaa14b9f14193e47c2c9f58ec50281d77c41a0e036a)
---

## worklog 

[worklog-164](https://youtu.be/hkCeGkhDGLg)

---

## feedback

---

## proposal

**Comment by ninabreznik** [comment]
Hi,

I prepared a few task proposals for you. Can you please update the issue above with the new tasks!

TODO1: Can you update the table to have 3 columns: `no.`, `name` (with link to Github) and `organization` (instead of `s.no`, `names`, `socials`
![Screenshot_2023-11-12_02-52-27](https://github.com/dat-ecosystem/dat-ecosystem/assets/1076427/c77b9161-444e-44b8-8054-7b7a72fbe2a0)

TODO2: can you please update our members with this list of members:

[Alexander Cobleigh](https://github.com/cblgh) / Cabal
[Alexander Praetorius](https://github.com/serapath) /  DatDot & WizardAmigos
[Diego Paez](https://github.com/dpaez) / Geut Studio
[Franz Heinzmann](https://github.com/frando) / Sonar
[Kevin Faaborg](https://github.com/zootella) / Ara
[Nina Breznik](https://github.com/nbreznik) / DatDot & WizardAmigos

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.27`

- update our_members_v0.0.1 - `34min`
   - update and add link to the our_members component with data file
   - create - worklog comment, and task- `8min`
   - @output 📦 [our_members_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/79fbd7c59cfe6b4c0b8c0bc0383bc192685867c0)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback

---

## proposal
