### ISSUE TITLE
code - tools component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#28]
#4 

### `todo`

- [x] create tools component
   - `@input` 📦 [`window_bar_v0.0.4`](https://github.com/dat-ecosystem/dat-ecosystem/commit/96958e3b14e4f2745fd4c7e558a1b70f768678b7#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add tools icons
    - `@output` 📦 [`tools_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/0e6d0841d7894042dfbe7736c848c2ef549b92fd#diff-2139a095da8ed63ac0ec02c90372f10f72ca83ea33f7548ab140f1f505a6d5af) from [`comment`]()
   
---

- [x] finalize tools_v?.?.?
   - `@output` :question: `tools_v?.?.?` from `comment`
     - next #23

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- create tools component  - `31min`
   - add tools icons
   - create - worklog comment, and task- `10min`
   - `@output` 📦 [`tools_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/0e6d0841d7894042dfbe7736c848c2ef549b92fd#diff-2139a095da8ed63ac0ec02c90372f10f72ca83ea33f7548ab140f1f505a6d5af)
---

## worklog 

[worklog-164](https://youtu.be/hkCeGkhDGLg)

---

## feedback

---

## proposal

**Comment by ninabreznik** [comment]
## `@TODO`

- [ ] add tools
- [ ] find logos online

- Mastodon https://fosstodon.org/@dat_ecosystem
- OpenCollective https://opencollective.com/dat
- Twitter https://twitter.com/dat_ecosystem
- Github https://github.com/dat-ecosystem
- Cabal https://github.com/dat-ecosystem/dat-ecosystem.github.io/blob/main/README.md#connect-to-cabal-with-cli-or-download-cabal-desktop
- Jitsi https://meet.jit.si/dat-ecosystem
- Discord https://discord.gg/egsvGc9TkQ
- BigBlueButton https://bigbluebutton.org/
- YouTube https://www.youtube.com/@DatEcosystem
- HackMD https://hackmd.io/@T6Wf5EsOQKe-6wyPjJPtuw/Hycn0F63r/%2Fx_4tQHwtT3u7vrksrposHw

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.27`

- update tools_v0.0.1
   - gather tools svg icons
   - create keet's logo in svg
   - update the tools contents
   - `@output` 📦 [tools_v0.0.2](https://github.com/dat-ecosystem/dat-ecosystem/issues/28)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback

---

## proposal
