### ISSUE TITLE
code - the dat component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#29]
#4 

### `todo`

- [x] create the_dat component
   - `@input` 📦 [`window_bar_v0.0.5`](https://github.com/dat-ecosystem/dat-ecosystem/commit/af492a308773dd9aa03216153addbbe5332627a3#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - [x] add the window_bar
   - [x] code the full-screen protocol
   - [x] code a placeholder for VR
    - `@output` 📦 [`the_dat_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/af492a308773dd9aa03216153addbbe5332627a3#diff-c639b2c8175d4f7837787ff14c3dab217b7b34420a36d994ca1a35162bf8293a) from [`comment`]()
   
---

- [x] finalize the_dat_v?.?.?
   - `@output` :question: `the_dat_v?.?.?` from `comment`
     - next #23

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- create the_dat component - `1h18min`
   - add the window_bar
   - code the full-screen protocol
   - code a placeholder for VR
   - create - worklog comment, and task- `9min`
   - `@output` 📦[the_dat_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/af492a308773dd9aa03216153addbbe5332627a3#diff-c639b2c8175d4f7837787ff14c3dab217b7b34420a36d994ca1a35162bf8293a)

---

## worklog 

[worklog-167](https://youtu.be/eTp45j_Dlqk)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.17`

- update the_dat_v0.0.1
   - convert the dat icon to svg - `24min`
   - convert vr icon to svg - `19min`
   - convert full-screen icon to svg - `16min`
   - convert plus icon to svg - `11min`
   - add all the icons - `5min
   - create - worklog comment, and task- `13min`
   - `@output` 📦 [the_dat_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/162d99db75d46e3f8a066770a5bc2615dd555a61#diff-c639b2c8175d4f7837787ff14c3dab217b7b34420a36d994ca1a35162bf8293a)

---

## worklog 

[worklog-169](https://youtu.be/qrFhSCVUESM)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.27`

- update the_dat_v0.0.2 - `10min`
   - update the dat title to the visualization
   - update the iframe link
   - create - worklog comment, and task- `9min`
   - `@output` 📦 [the_dat_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/e6365855c96bfc3d4f437e4976c3382c691e3cef#diff-7830205af27e474c777e86030ad7953ca2e7912e3276f1d1a8d2bed075da4d0c)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback

---

## proposal
