### ISSUE TITLE
code - page

### ISSUE THREAD

**Issue by serapath** [dat-ecosystem/dat-ecosystem#3]
## `@todo`
* [ ] implement webpage
  * `@input` :package: {link-to-wireframes-etc...} from {issue number}
  * [ ] implement button component
    * `@input` :package: {link-to-wireframes-etc...} from {issue number}
    * `@output` :question: `button component`
  * [ ] implement navbar component
    * `@input` :package: {link-to-wireframes-etc...} from {issue number}
    * `@output` :question: `navbar component`
  * [ ] implement page component
    * `@input` :package: {link-to-wireframes-etc...} from {issue number}
    * `@input` :question: `navbar component`
    * `@input` :question: `button component`
    * [ ] use components to put together the page component
    * `@output` :question: `webpage component`
  * [ ] implement dat-ecosystem page
    * `@input` :question: `webpage component`
    * [ ] use webpage component to implement page
    * `@output` :question: `dat-ecosystem page`
```

**Comment by serapath** [comment]
**feedback `2023.06.08`**

I updated the project structure and linked all issues properly and also closed lots of issues that were basically done and took their final output to link it here.

* The **dat ecosystem p2p garden** isn't done yet, but we paused that for a bit.
* The **timeline component** didn't process the last feedback to make it more github like

Otherwise, a few other issues had unprocessed feedback which i collected and put it below into this comment here:

------------------------------------
# open feedback remaining from closed issues
1. The dominant color in the theme should be green, so maybe all buttons should be green by default and maybe pink on user highlight/focus

2. we need the "launcher" to open a program again when it gets closed :-)

3. We need a separate icon for every program we use and they should be unique.
  * Every program is an "app".
    * So the folder icon is for the file explorer showing folders (e.g. tools folder in "info")
    * The timeline looks similar to projects, but they are not.
      * timeline app should probably have some sort of "calendar icon"
      * projects app might have maybe a "business card" icon or something like that

Basically, for every program, can you check if we re-use it or if it is new and use an icon that represents the program? (also we have to give each program a name)
Every window with a window bar represents a program/app.

e.g. needs a pixel version of a simple [pdf icon](https://www.google.com/imgres?imgurl=https%3A%2F%2Fimg.icons8.com%2Fios7%2F600w%2F000000%2Fpdf.png&tbnid=iz95JDOGzq4OMM&vet=12ahUKEwjm-uyczvn-AhXFtEwKHWTAC38QMyg6egQIARBW..i&imgrefurl=https%3A%2F%2Ficons8.com%2Ficons%2Fset%2Fpdf&docid=2Wir-cIESnL75M&w=600&h=600&q=pdf%20pixel%20icon&ved=2ahUKEwjm-uyczvn-AhXFtEwKHWTAC38QMyg6egQIARBW)


------------------------------------
# coming soon placeholder page
from closed issue `112` - feedback from `2023.05.16`
https://github.com/dat-ecosystem/organization/issues/112

First feedback for the close `x` button.
Yes, i agree it does not make much sense on the "coming soon" banner.
So this is fine.
The navbar tab represents a specific program, imagine it like a "PDF".
Or even just an HTML previewer.
Or a "slide deck" program (imagine for example if the `home`, `projects`, `timeline` and `growth program` where slide decks, but each slide is a program and it's fixed.

It's a new thing. It doesn't really have any prior example i would be aware of.
But if we just create such a presentation format, we could store a file that defines the programs and content and the order in which they are displayed and then we can open that "file" with the specific viewer program, which we open 4 times (for each navbar tab).

Also, a navbar tab can also just represent another desktop. a desktop also being just yet another program. (for example the pinned "info" tab).

That way we still get something systematic that a user can learn and understand and later use for their own customized version of the page, instead of us hard coding some very dat-ecosystem webpage specific layout.

---

### regarding banner choice
I was checking back and forth and both banner proposals have pros and cons.
I agree with your argument too, but i checked back after one hour and then again after another hour and slowly things started shifting and I felt the colorful big banner is better.
So I asked Nina what she thinks and others too and they all said the colorful one is the more inviting one. It also shows nature, maybe even a bit of a wild  garden or at least national park. We also don't use that image yet and people can actually look at it for a longer time to explore the image and imagine what could all of this mean.

I think to spark imagination and to make things more friendly and interesting, let's go with the colorful banner.
The other banner we also already have on the home page, so it's not lost either.
It also can finally introduce the two helper robots :-)


------------------------------------
# project page 
open feedback remaining from `2015.05.16`
https://github.com/dat-ecosystem/organization/issues/98

+1 for the "THE DAT" icon. awesome improvement. thanks.
+1 for the webXR mode icon. the glasses are better.

Last time you shared a few words that convinced me the entire navbar as such should have:
1. an option to make the entire website fullscreen
  * can you remove fullscreen icon from "THE DAT"? (users can dblclck window bar for it)
  * can you move the fullscreen icon into the navbar after theme icon?
2. and we also need two more "socials"
  * matrix chat https://commons.wikimedia.org/wiki/File:Matrix_icon.svg
  * mastodon account https://www.iconbolt.com/iconsets/remix-icon-fill/mastodon
  

### regarding close icon
Still same issue,when a user closes a window, we now need the "launcher".

Initially I thought of the navbar items as named "desktops", but after your last feedback, I thought of the navbar icons as "apps" as you described. Still, the "info" tab feels like a pinned browser tab and it still shows a desktop, hence I'd say the navbar items are apps, but desktop is also a special kind of app.

Giving windows on `home`, `projects`, `timeline`, `garden` a closing `x` icon makes them desktops, but not giving them that closing icon makes them some sort of special curated wall.
Both seems fine to me.

Do you prefer the desktop, because you added the `x`?

Even though we do not yet have a fully featured real desktop, we should aim for giving user that impression and one way of doing it, is the "launcher".

1. on a desktop, once a window is closed,it needs to be possible to open it again.
2. the navbar itself should also have an option to re-open or open new navbar tabs and also close them.

maybe the `dat logo` itself can be a dropdown menu to list and start programs
Maybe we can do it in the following way:
1. prefix navbar tab with program icon
2. postfix navbar tab with a `+` the user can click to open/add new programs to the desktop

The `+` button after the text in each navbar tab shows a dropdown menu from which a user can select actions for that program. In the case of a desktop, action means to launch a new program for example :-)
