### ISSUE TITLE
code - month card component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#30]
#4

## `todo`

- [x] create month_card_v0.0.1
   - `@input` 📦 [`button_v0.0.8`](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-b360ac18a2e2bc691a494c8e91d3c137e1e2195053849b2bdacbb34cd4bab9c4) from #1 
   - [x] code month_card component
    - `@output` 📦 [`month_card_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-31754c06cf28b3c6330c5b1542ec2e16ae344002fb38c8f794679159dc7ec5df) from [comment]()
   
---

- [x] finalize month_card_v?.?.?
   - `@output` :question: `month_card_v?.?.?` from `comment`
     - next `month_filter`

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.29`

- create month_card_v0.0.1 - `1h23min`
   - code month_card component
   - code month_card protocol
   - create - worklog comment, and task- `13min`
   - `@output` 📦 [month_card_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-31754c06cf28b3c6330c5b1542ec2e16ae344002fb38c8f794679159dc7ec5df)

---

## worklog 

[worklog-166](https://youtu.be/xVAqdOusnGc)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.17`

- update month_card_v0.0.1 - `24min`
   - code month_card protocol
   - code function to toggle days
   - create - worklog comment, and task- `8min`
   - `@output` 📦 [month_card_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/a86532327864adc0c34a22ab3c77e32246d83c41#diff-31754c06cf28b3c6330c5b1542ec2e16ae344002fb38c8f794679159dc7ec5df)
---

## worklog 

[worklog-169](https://youtu.be/qrFhSCVUESM)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.11`

- update month_card_v0.0.2
   - fix - month card style - `16min`
   - update - border styles for buttons
   - create tasks and logs - `14min`
   - `@output` 📦 [month_card_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/46226887780886881676fe75beb3ca574cd75d15)

---

## worklog 

[worklog-181](https://youtu.be/ShRemmsZ1y0)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.29`

- update month_card_v0.0.3
   - code day toggle visibility function - `50min`
   - create and update tasks - `11min`
   - @output 📦 [month_card_v0.0.4](https://github.com/Mehrabbruno/dat-ecosystem/commit/afca623e4de6928398916c4cc3b6bfcbb07cb628#diff-3065e9f9a57aa1303092e65c78ea0e14a9b9341376514c2a6eaa498a45f828ec)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback
  
---

## proposal
