### ISSUE TITLE
Update - app_icon Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#31]
## `todo`

- [x] Update app_icon_v0.1.0
   - [x] update the app_icon component
   - `@ouptut` :package: [`app_icon_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-icon/app-icon.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/26#issuecomment-1913554225)

---

- [ ] Finalize app_icon_v0.1.?
   - [ ] code app_icon
   - `@output` :package: `app_icon_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update app_icon_v0.1.0
   - update the app_icon component
   - `@ouptut` :package: [`app_icon_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-icon/app-icon.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
