### ISSUE TITLE
code - month filter component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#31]
#4

## `todo`

- [x] create month_filter_v0.0.1
   - `@input` 📦[`month_card_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-31754c06cf28b3c6330c5b1542ec2e16ae344002fb38c8f794679159dc7ec5df) from #30 
   - [x] code month_filter protocol
    - `@output` 📦 [`month_filter_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-5e18736007847b3bcee8244fca717b61f2b62646e85229d0e8f70d2684ffe601) from [comment]()
   
---

- [x] finalize month_filter_v?.?.?
   - `@output` :question: `month_filter_v?.?.?` from `comment`
     - next `month_filter`

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.30`

- create month_filter_v0.0.1  - `2h10min`
   - code month_filter protocol
   - create - worklog comment, and task- `11min`
   - `@output` 📦 [month_filter_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-5e18736007847b3bcee8244fca717b61f2b62646e85229d0e8f70d2684ffe601)

---

## worklog 

[worklog-166](https://youtu.be/xVAqdOusnGc)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.17`

- update month_filter_v0.0.1 - `23min`
   - code toggle month function
   - code active date protocol
   - create - worklog comment, and task- `10min`
   - `@output` 📦 [month_filter_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/a86532327864adc0c34a22ab3c77e32246d83c41#diff-5e18736007847b3bcee8244fca717b61f2b62646e85229d0e8f70d2684ffe601)

---

## worklog 

[worklog-169](https://youtu.be/qrFhSCVUESM)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.11`

- update month_filter_v0.0.2
   - fix the x-axis scroll - `50min`
   - fix the scrollbar issues on different browser - `23min`
   - create tasks and logs - `13min`
   - `@output` 📦 [month_filter_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/9cb7fbde392f559096e3afb8d4e5319164522e78#diff-e3026744888a72b061af5e6e574838c1ef278013f46481db4ac1dcf07d5fe796)

---

## worklog 

[worklog-181](https://youtu.be/ShRemmsZ1y0)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.29`

- update month_filter_v0.0.3 - `54min`
   - code leap year condition
   - update calendar function
   - create and update tasks - `6min`
   - @output 📦 [month_filter_v0.0.4](https://github.com/Mehrabbruno/dat-ecosystem/commit/afca623e4de6928398916c4cc3b6bfcbb07cb628#diff-e3026744888a72b061af5e6e574838c1ef278013f46481db4ac1dcf07d5fe796)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback
  
---

## proposal
