### ISSUE TITLE
code - year filter component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#32]
#4

## `todo`

- [x] create year_filter_v0.0.1
   - [x] code code_filter protocol
    - `@output` 📦 [`year_filter_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-7eea01a47c25c9d3fe754b14337aa6e69a86d49727dea49ac9d0129e97b10c1e) from [comment]()
   
---

- [x] finalize year_filter_v?.?.?
   - `@output` :question: `year_filter_v?.?.?` from `comment`
     - next `timeline_filter`

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.30`

- create year_filter_v0.0.1  - `2h18min`
   - code year_filter protocol
   - create - worklog comment, and task- `16min`
   - `@output` 📦 [year_filter_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-7eea01a47c25c9d3fe754b14337aa6e69a86d49727dea49ac9d0129e97b10c1e)

---

## worklog 

[worklog-166](https://youtu.be/xVAqdOusnGc)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.17`

- update year_filter_v0.0.1 - `30min`
   - code updating year on scroll
   - create - worklog comment, and task- `11min`
   - `@output` 📦 [year_filter_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/7c49ddc177b401ce2ae2cd8fd4b720f327807825#diff-7eea01a47c25c9d3fe754b14337aa6e69a86d49727dea49ac9d0129e97b10c1e)

---

## worklog 

[worklog-169](https://youtu.be/qrFhSCVUESM)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.29`

- update year_filter_v0.0.2
   - make the year filter data dynamic - `7min`
   - create and log tasks - `6min`
   - `@output` 📦 [year_filter_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/afca623e4de6928398916c4cc3b6bfcbb07cb628#diff-499289be094a14c8132aeccd6ae0dae58f7c2258de2f20e7369521a288cd54b7)

---

## worklog 

[worklog-184](https://youtu.be/jfvVVjHzIog)

---

## feedback
  
---

## proposal
