### ISSUE TITLE
Update - navbar Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#33]
## `todo`

- [x] Update navbar_v0.1.0
   - `@input` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from #3 
   - [x] add open_collective to socials
   - [x] changed terminal and theme buttons color
   - [x] on mobile - scroll_down should close nav_menu
   - `@output` :package: [`navbar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/355575f50dc61c43d3f80aa7b839079970acd9ab#diff-1ea515a4cb7ff9cdad4089e04548813e9f7cbd296d817b41631101739bf6e869) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/32#issuecomment-1913636375)

---

- [ ] Finalize navbar_v0.1.?
   - [ ] code navbar
   - `@output` :package: `navbar_v0.1.?` from `comment`
