### ISSUE TITLE
code - timeline filter component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#33]
#4

## `todo`

- [x] create timeline_filter_v0.0.1
   - [x] add month buttons
   - [x] code protocol between month button
   - [x] add year buttons
   - [x] code protocol between year button
   - [x] code timeline protocol
    - `@output` 📦 [`timeline_filter_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-589617ce51b1143f5958a4da93a1fb1f92f4850016049438dbffe2e8b46c9a6a) from [comment]()
   
---

- [x] finalize timeline_filter_v?.?.?
   - `@output` :question: `timeline_filter_v?.?.?` from `comment`
     - next `timeline_filter`

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.30`

- create timeline_filter_v0.0.1
   - add month buttons - `1h23min`
   - code protocol between month button
   - add year buttons - `58min`
   - code protocol between year button
   - code timeline_filter protocol - `1h`
   - create - worklog comment, and task- `16min`
   - `@output` 📦 [timeline_filter_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-589617ce51b1143f5958a4da93a1fb1f92f4850016049438dbffe2e8b46c9a6a)

---

## worklog 

[worklog-166](https://youtu.be/xVAqdOusnGc)

---

## feedback

---

## proposal
