### ISSUE TITLE
code - app timeline component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#34]
#4

## `todo`

- [x] create app_timeline_v0.0.1
   - `@input` 📦 [timeline_filter_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-589617ce51b1143f5958a4da93a1fb1f92f4850016049438dbffe2e8b46c9a6a) from #33 
   - `@input` 📦 [timeline_card_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-931aab9f12c22b4ea8c8350eb4d25d1b3338f7d191b851edc3f3bd548c8aef8f) from #9 
   - `@input` 📦 [window_bar_v0.0.5](https://github.com/dat-ecosystem/dat-ecosystem/commit/af492a308773dd9aa03216153addbbe5332627a3#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - `@input` 📦 [year_filter_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-7eea01a47c25c9d3fe754b14337aa6e69a86d49727dea49ac9d0129e97b10c1e) from #32 
   - `@input` 📦 [month_filter_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-5e18736007847b3bcee8244fca717b61f2b62646e85229d0e8f70d2684ffe601) from #31 
   - [x] code app timeline protocol
   - [x] code protocol between month_filter, year_filter, and month_card
    - `@output` 📦 [`app_timeline_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-b1b1c2abcb428c7b82cc544eeb216fe3309e6fa75b4b87e038d739b4f588bc33) from [comment](https://github.com/dat-ecosystem/dat-ecosystem/issues/33#issuecomment-1656946780)
   
---

- [x] finalize app_timeline_v?.?.?
   - `@output` :question: `app_timeline_v?.?.?` from `comment`
     - next #22

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.30`

- create app_timeline_v0.0.1 - `6hr`
   - code app timeline protocol
   - code protocol between month_filter, year_filter, and month_card
   - create - worklog comment, and task- `16min`
   - `@output` 📦 [timeline_filter_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-589617ce51b1143f5958a4da93a1fb1f92f4850016049438dbffe2e8b46c9a6a)

---

## worklog 

[worklog-166](https://youtu.be/xVAqdOusnGc)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.17`

- update app_timeline_v0.0.1  - `1h8min`
   - update protocol
      - code updating calendar
   - create - worklog comment, and task- `11min`
   - `@output` 📦[app_timeline_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/a86532327864adc0c34a22ab3c77e32246d83c41#diff-b1b1c2abcb428c7b82cc544eeb216fe3309e6fa75b4b87e038d739b4f588bc33) 

---

## worklog 

[worklog-169](https://youtu.be/qrFhSCVUESM)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.17`

- update app_timeline_v0.0.2
   - sort timeline_card - `20min`
   - group timeline_card by year - `15min`
   - update protocol - `40min`
   - add scroll onclick feature - `35min`
   - code tracking offset
   - create - worklog comment, and task- `13min`
   - `@output` 📦 [app_timeline_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/7c49ddc177b401ce2ae2cd8fd4b720f327807825)

---

## worklog 

[worklog-169](https://youtu.be/qrFhSCVUESM)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.11.11`

- update app_timeline_v0.0.3 - `18min`
   - fix the issue on chrome
   - `@output` 📦 [update app_timeline_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/6ff16cf64769d872a36d94959642dd10236c71bd#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451)

---

## worklog 

[worklog-181](https://youtu.be/ShRemmsZ1y0)

---

## feedback

---

## proposal

**Comment by ninabreznik** [comment]
## `@TODO`

- `@input`: https://github.com/dat-ecosystem/dat-ecosystem.github.io/blob/main/timeline.js
- [ ] add events to the timeline

**Comment by ninabreznik** [comment]
## Comment for worklog 184

- I think we will need a scroll on the tags dropdown as there is really many options. Maybe we could make a dropdown with option to add a scroll after there is more than X items. So that if any other dropdown gets more filters in the future, it will automatically add the scroll for it.
    - time on the cards should be optional in the json file. If present, we display it, if not, we don't display any time.
    - 100% height for single card seems reasonable, will also try it out and see how it feels
    
**`calendar`:**
  - we should only display the events from the selected day
  - the icon for opening and closing the calendar should change on click
  - opening the calendar shouldn't change the window height, instead calendar should open same as the dropdowns do (over the content) and it should not go over the scroll bar on the right side
  - links should open in the new tab (if there is many links
  
See also comment on your previous worklog
https://github.com/dat-ecosystem/dat-ecosystem/issues/34#issuecomment-1806780108

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.20`

- update app_timeline_v0.0.7 
   - code timeline sorting function - `44min`
   - show empty state when no data is available - `24min`
   - fix month_filter width problem when toggles - `27min`
   - create and update tasks - `7min`
   - `@output` 📦 [app_timeline_v0.0.8](https://github.com/Mehrabbruno/dat-ecosystem/commit/881a26bada669a019653f538481f934b8b02d598#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451)

---

## worklog 

[worklog-188](https://youtu.be/K7D_jrcDjIc)

---

## feedback
  
---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.29`

- update app_timeline_v0.0.8
   - fix timeline text - `4min`
   - fix timeline filter - `7min`
   - fix highlight card bug - `12min`
   - fix search bug - `24min`
   - `@output` 📦 [app_timeline_v0.0.9](https://github.com/Mehrabbruno/dat-ecosystem/commit/53f31a67cd8c015d59f4d1cd80eff76d57a6451d#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451)

---

- update app_timeline_v0.0.9
   - fix scroll bug on cards - `32min`
   - update year filter - `54min`
   - update calendar on filter - `1h6min`
   - `@output` 📦 [app_timeline_v0.0.10](https://github.com/Mehrabbruno/dat-ecosystem/commit/3903a006fcb6814d4d740115bbd055109676f8e0#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451)

---

- update app_timeline_v0.0.10
   - make multiple cards selected based on date - `54min`
   - create and update tasks - `14min`
   - `@output` 📦 [app_timeline_v0.0.11](https://github.com/Mehrabbruno/dat-ecosystem/commit/3d667641a4ad2ac60ee3b6d9e0dc7ad3dd839340#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451)

---

## worklog 

[worklog-190](https://youtu.be/g8-NA3ogczk)

---

## feedback
  
---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2024.01.13`

- update app_timeline_v0.0.11
   - Add dividers between cards on yearly manner - `32min`
   - Moved data from timeline to data.json - `5min`
   - Add scroll in Article tag and others - `57min`
   - Fix color and box on timeline - `12min`
   - `@output` 📦 [app_timeline_v0.0.12](https://github.com/Mehrabbruno/dat-ecosystem/commit/491898cc2aa86c6c04b1b078a49f603b86d03961#diff-31751a4239a2d948067baa01d3039ca4f773d66b4e719ee0138a2ff81cddc451)

---

## worklog 

[worklog-191]()

---

## feedback
  
---

## proposal
