### ISSUE TITLE
code - scroll horizontal component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#35]
#4

## `todo`

- [x] create scroll_bar_horizontal_v0.0.1
   - `@input` 📦 [button_v0.0.8](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-b360ac18a2e2bc691a494c8e91d3c137e1e2195053849b2bdacbb34cd4bab9c4) from #1 
   - [x] code scroll_bar_horizontal
    - `@output` 📦 [`scroll_bar_horizontal_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-4320e4a91f7d9cdd7d2df57c6fb077f4475719993f0ba410f5cbc27b9e59883d) from [comment]()
   
---

- [x] finalize scroll_bar_horizontal_v?.?.?
   - `@output` :question: `scroll_bar_horizontal_v?.?.?` from `comment`
     - next `tbd`

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.30`

- create scroll_bar_horizontal_v0.0.1 - `1hr30min`
   - code scroll_bar_horizontal protocol
   - create - worklog comment, and task- `12min`
   - `@output` 📦 [scroll_bar_horizontal_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-4320e4a91f7d9cdd7d2df57c6fb077f4475719993f0ba410f5cbc27b9e59883d)

---

## worklog 

[worklog-166](https://youtu.be/xVAqdOusnGc)

---

## feedback

---

## proposal
