### ISSUE TITLE
code - tab window component 

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#36]
#4

## `todo`

- [x] create tab_window_v0.0.1
   - [x] code placeholder tab_windows to be used as open terminal tabs
    - `@output` 📦 [`tab_window_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/cb1afc5e39f1507d9b9c4ead6249ffa55ea93d21#diff-48ea9997b5d63c69b20db2442dcc7c19231472ca34d3a2035de46f9ffcba8f85) from [comment]()
   
---

- [x] finalize tab_window_v?.?.?
   - `@output` :question: `tab_window_v?.?.?` from `comment`
     - next `terminal_component`

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.03`

- create tab_window_v0.0.1 - `20min`
   - code placeholder tab_windows to be used as open terminal tabs
   - create - worklog comment, and task- `12min`
   - `@output` 📦 [tab_window_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/cb1afc5e39f1507d9b9c4ead6249ffa55ea93d21#diff-48ea9997b5d63c69b20db2442dcc7c19231472ca34d3a2035de46f9ffcba8f85)

---

## worklog 

[worklog-167](https://youtu.be/eTp45j_Dlqk)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.29`

- update tab_window_v0.0.1 - `2h22min`
   - update tab_windows with basic commands
   - create and update tasks - `9min`
   - `@output` 📦[tab_window_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/53f31a67cd8c015d59f4d1cd80eff76d57a6451d#diff-8d3dff508432d2fd96f01ada43467a0d4cc246da48be13676a4d0d384c16dd98)

---

## worklog 

[worklog-190](https://youtu.be/g8-NA3ogczk)

---

## feedback
  
---

## proposal

**Comment by Mehrabbruno** [comment]
tasks - 2024.01.13

- update tab_window_v0.0.2
   - update command description and bug fixes
   - `@output` 📦 [tab_window_v0.0.3](https://github.com/Mehrabbruno/dat-ecosystem/commit/491898cc2aa86c6c04b1b078a49f603b86d03961#diff-8d3dff508432d2fd96f01ada43467a0d4cc246da48be13676a4d0d384c16dd98)
---

## worklog 

[worklog-191](https://youtu.be/ZNgxiVrEotw)

---

## feedback
  
---

## proposal
