### ISSUE TITLE
code - terminal component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#37]
#4

## `todo`

- [x] create terminal_v0.0.1
   - `@input` 📦 [tab_window_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/cb1afc5e39f1507d9b9c4ead6249ffa55ea93d21#diff-48ea9997b5d63c69b20db2442dcc7c19231472ca34d3a2035de46f9ffcba8f85) from #36 
   - `@input` 📦 [button_v0.0.9](https://github.com/dat-ecosystem/dat-ecosystem/commit/cb1afc5e39f1507d9b9c4ead6249ffa55ea93d21#diff-e4dfbf7e0c2ecad289c731c77ad9ee66cd814fcfd6e8532932b3a25cd2be62cd) from #1 
   - `@input` 📦 [scroll_bar_horizontal_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/237c10b5c1b643fe1fd0600059a1f61ca79e19e9#diff-4320e4a91f7d9cdd7d2df57c6fb077f4475719993f0ba410f5cbc27b9e59883d) from #35 
   - [x] code the terminal component
   - [x] code terminal protocols
      - [x] code tab switch protocol
      - [x] code add tab protocol
      - [x] code closing terminal protocol
      - [x] code toggling terminal from navbar protocol
   - [x] code terminal footer
      - [x] code terminal tab container
         - [x] add tab buttons
         - [x] add scrollbar
      - [x] add terminal icon buttons
    - `@output` 📦 [`terminal_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/cb1afc5e39f1507d9b9c4ead6249ffa55ea93d21#diff-6c4a13b234c197f9c27536de71fa34e4a2aec4afed306bed2447e2cc3c217557) from [comment]()
   
---

- [x] finalize terminal_v?.?.?
   - `@output` :question: `terminal_v?.?.?` from `comment`
     - next #4

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.03`

- create terminal_v0.0.1 - `1h`
   -  code the terminal component
   - code terminal protocols - `2h57min`
      - code tab switch protocol
      - code add tab protocol
      - code closing terminal protocol
      - code toggling terminal from navbar protocol
   - code terminal footer - `49min`
      - code terminal tab container
         - add tab buttons
         - add scrollbar
      - add terminal icon buttons - `26min`
   - create - worklog comment, and task- `16min`
   - `@output` 📦 [terminal_v0.0.1](https://github.com/dat-ecosystem/dat-ecosystem/commit/cb1afc5e39f1507d9b9c4ead6249ffa55ea93d21#diff-6c4a13b234c197f9c27536de71fa34e4a2aec4afed306bed2447e2cc3c217557)

---

## worklog 

[worklog-167](https://youtu.be/eTp45j_Dlqk)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.13.12`**

having not watched the latest worklog above, here are some additional thoughts i wanted to share after discussing with nina about what the terminal should initially be able to do as a very limited more "gimmicky" thing:

```js
// how about instead we display some sort of minimal terminal message with a hint to type
// .help() // for more info ...or something...
// and if somebody does, we print out a list of commands ... basically something to list
// currently available data and a way to navigate the page in a very basic fashion.
// e.g.
.help()
// { help: 'description of help', list: 'description of list command', goto: '...', read: '...' }

.list()
// ['info/', 'home/', 'projects/', 'timeline/']
.list('info')
// ['mission_statement.md', 'important_documents.md', 'our_members.md', 'tools/']

.goto('projects/') // focuses projects page
.goto('timeline/') // focuses timeline

// and then maybe user can type more to show data in terminal, like
.read('projects') // prints all project card data as json to terminal
// same as `.read('projects/index.json')`
.read('timeline/index.json') // prints all timeline card data as json to terminal
.read('info/mission_statement.md') // prints markdown content of mission statement to terminal
.read('info') // prints `undefined` ...because there is no `.index.json`
```

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.29`

- update terminal_v0.0.1 - `1h3min`
   -  updated terminal protocol
   - close the terminal on close btn
   - create and update tasks - `5min`
   - `@output` 📦[terminal_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/53f31a67cd8c015d59f4d1cd80eff76d57a6451d#diff-5afa730b6ca6e9826e433fb614050ed7a4f78e7c9fc1212d4b820ffef81f8714)

---

## worklog 

[worklog-190](https://youtu.be/g8-NA3ogczk)

---

## feedback
  
---

## proposal
