### ISSUE TITLE
code - coming_soon component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#38]
#4

## `todo`

- [x] create coming_soon_v0.0.1
   - `@input` 📦 [window_bar_v0.0.5](https://github.com/dat-ecosystem/dat-ecosystem/commit/af492a308773dd9aa03216153addbbe5332627a3#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1) from #5 
   - `@input` 📦 [button_v0.0.9](https://github.com/dat-ecosystem/dat-ecosystem/commit/cb1afc5e39f1507d9b9c4ead6249ffa55ea93d21#diff-e4dfbf7e0c2ecad289c731c77ad9ee66cd814fcfd6e8532932b3a25cd2be62cd) from #1 
   - [x] code in the window bar
   - [x] add a placeholder image
   - [x] add placeholder text
    - `@output` 📦 [`coming_soon_v0.0.1`](https://github.com/Mehrabbruno/dat-ecosystem/commit/0af6ee3d3e4055f32333193a696459675c74a363#diff-418c1d5bc1618fe1b199726f5d045643260245371b2d2087c7cdb06908a43887) from [comment]()
   
---

- [x] finalize coming_soon_v?.?.?
   - `@output` :question: `coming_soon_v?.?.?` from `comment`
     - next #21

**Comment by Mehrabbruno** [comment]
### tasks - `2023.08.17`

- create coming_soon_v0.0.1  - `28min`
   - code in the window bar
   - add a placeholder image
   - add placeholder text
   - create - worklog comment, and task- `9min`
   - `@output` 📦[window_bar_v0.0.5](https://github.com/dat-ecosystem/dat-ecosystem/commit/af492a308773dd9aa03216153addbbe5332627a3#diff-cf003479958e15a1c7d21063aba9126e72fb71d89aee5117fc633fb4a1bc6cc1)

---

## worklog 

[worklog-169](https://youtu.be/qrFhSCVUESM)

---

## feedback

---

## proposal

**Comment by ninabreznik** [comment]
Make the image same size as it is on the home page, otherwise it is very hard to see the project logos and the text coming soon!

**Comment by Mehrabbruno** [comment]
### tasks - `2023.12.20`

- update coming_soon_v0.0.1 
   - update image size - `5min`
   - `@output` 📦 [coming_soon_v0.0.2](https://github.com/Mehrabbruno/dat-ecosystem/commit/dcde5b75a1678864dee5081cddeea72f911246e3#diff-4688d3985a8beb40b422895e86da704f23952914f9a86b08623114620e226387)

---

## worklog 

[worklog-188](https://youtu.be/K7D_jrcDjIc)

---

## feedback
  
---

## proposal
