### ISSUE TITLE
Update - window_bar component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#4]
## todo

- [x] Update window_bar_v0.1.0
   - `@input` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from #3 
   - [x] Removed close_buttons from home/projects/dat-garden and timeline pages
   - `@output` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/f83a934887e0b4225650ca2dd13656a5109f021e#diff-91626448e6826c9c93db0af55de8a2e7a637957cae267bec8cc83370a7b8a918) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/3#issuecomment-1913281065)

---

- [ ] Finalize window_bar_v0.1.?
   - Code window_bar
   - `@output` :package: `window_bar_v0.1.?` from `comment`

**Comment by alyhxn** [comment]
### tasks - `2024.01.27`
- Update window_bar_v0.1.0
   - Removed close_buttons from home/projects/dat-garden and timeline pages - `16min`
   - Created and logged tasks - `14min`
   - `@output` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/commit/f83a934887e0b4225650ca2dd13656a5109f021e#diff-91626448e6826c9c93db0af55de8a2e7a637957cae267bec8cc83370a7b8a918)

---

### worklog

[worklog-196](https://youtu.be/Y69DqGC5wo0)

---

### feedback

---

### proposals
