### ISSUE TITLE
continue - data.json_v0.0.1 component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#46]
#4 

## todo

- [x] Update data_json_v0.0.1
   - `@input` :package: [`data_json_v0.0.1`]
   - [x] move the content from home onto data.json file
   - [x] move the content from consortium onto data.json file
   - `@output` :package: [`data_json_v0.0.2`] from [comment]()

---

- [x] finalize data.json_v?.?.?
   - @output ❓ data.json_v?.?.? from comment
   - next #19 , #34

**Comment by alyhxn** [comment]
### tasks - `2024.01.18`

- Update data_json_v0.0.1 - `46min`
   - moved the content from home onto data.json file
   - moved the content from consortium onto data.json file
   - Created and logged tasks - `9min`
   - @output 📦 [`data_json_v0.0.2`](https://github.com/Mehrabbruno/dat-ecosystem/commit/cfa0e55a7e0962e65980ea597713c55a28efc7a9#diff-b8b1203bc269c67f71f8c3ce80a41da8ed415b72e20610e7e0a59aebab70caf6)
