### ISSUE TITLE
continue - app_timeline_mini_v0.0.3 component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#47]
#4 

## todo

- [x] update app_timeline_mini_v0.0.3
   - `@input` :package: [`app_timeline_mini_v0.0.3`](https://github.com/Mehrabbruno/dat-ecosystem/commit/70af80a757e36e1d3032445c447e293cdb6ba696#diff-0c394a5caf6bd14ce7b6642c6e12d87a729b33dbd7de84a2e11c16785f05deff)
   - [x] Make cards data sync with data.json
   - `@output` :package: [`app_timeline_mini_v0.0.3`](https://github.com/Mehrabbruno/dat-ecosystem/commit/327baf8ea50489b0df01151acaa4ca5cbbf053d3#diff-0c394a5caf6bd14ce7b6642c6e12d87a729b33dbd7de84a2e11c16785f05deff)
  
---

- [ ] finalize app_timeline_mini_v?.?.?
   - `@output` ❓ `app_timeline_mini_?.?.?` from `comment`
      - next #7

**Comment by alyhxn** [comment]
### tasks - `2024.01.19`

- update app_timeline_mini_v0.0.3 - `14min`
   - Made cards data sync with data.json
   - Created and logged tasks - `11min`
   - `@output` :package: [`app_timeline_mini_v0.0.4`](https://github.com/Mehrabbruno/dat-ecosystem/commit/327baf8ea50489b0df01151acaa4ca5cbbf053d3#diff-0c394a5caf6bd14ce7b6642c6e12d87a729b33dbd7de84a2e11c16785f05deff)

---

## worklog 

[worklog-194]()

---

## feedback
  
---

## proposal
