### ISSUE TITLE
Update - app_about_us Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#5]
## `todo`

- [x] Update app_about_us_v0.1.0
   - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #3 
  - [x] update the app_about_us component
  - `@output` :package:  [`app_about_us_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-about-us/app-about-us.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/4#issuecomment-1913285606)
 
---

- [ ] Finalize app_about_us_v0.1.?
   - [ ] code app_about_us
   - `@output` :package: `app_about_us_v0.1.?` from `comment`
   - next #11

**Comment by alyhxn** [comment]
### tasks - `2024.01.27`

- Update app_about_us_v0.1.0
   - update the app_about_us component
   - `@output` :package: [`app_about_us_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-about-us/app-about-us.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
