### ISSUE TITLE
Update - app_project_mini Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#6]
## `todo`

- [x] Update app_project_mini_v0.1.0
  - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #3 
  - `@input` :package: [`project_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/project-card/project-card.js) from #6 
  - [x] update the app_project_mini component
  - `@output` :package:  [`app_project_mini_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-projects-mini/app-projects-mini.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/5#issuecomment-1913301452)

---

- [ ] Finalize app_project_mini_v0.1.?
   - [ ] code app_project_mini
   - `@output` :package: `app_project_mini_v0.1.?` from `comment`
   - next #11

**Comment by alyhxn** [comment]
### tasks - `2024.01.27`

- Update app_project_mini_v0.1.0
  - update the app_project_mini component
  - `@output` :package:  [`app_project_mini_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-projects-mini/app-projects-mini.js)

### worklog

---

### feedback
Initialized the issue

---

### proposals
