### ISSUE TITLE
Update - project_card Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#7]
## `todo`

- [x] Update project_card_v0.1.0
   - `@input` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from #3
   - [x] update the project_card component
   - `@output` :package: [`project_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/project-card/project-card.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/6#issuecomment-1913304575)

---

- [ ] Finalize project_card_v0.1.?
   - [ ] code project_card component
   - `@output` :package: `project_card_v0.1.?` from `comment`
   - next #5

**Comment by alyhxn** [comment]
### tasks - `2024.01.27`

- Update project_card_v0.1.0
   - update the project_card component
   - `@output` :package: [`project_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/project-card/project-card.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
