### ISSUE TITLE
code - home_page component

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/dat-ecosystem#7]
#3 

### `todo`

- code home_page
   - `@input` 📦 [`home_page_v0.0.10`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1760-2784&t=i9jWdxjECWAyb6ri-4) from [dat-ecosystem website_homepage](https://github.com/dat-ecosystem/organization/issues/85)
   - `@input` 📦 [`window_bar_v0.0.1`]() from #5 
   - `@input` 🏭 [`app_cover_v0.0.1`]() from #6

**Comment by Mehrabbruno** [comment]
### tasks - `2023.05.26`

- code home_page_v0.0.1
   - created home_page file - `3min`
   - create worklog comment, task, issues and pull request - `5min`
   - `@output` 📦 [`home_page_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/c25b10717943c1c0a24918885ee44002cb70688f)

---

## worklog 

---

## feedback

- created homepage

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.05.026`**

see https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-dbdfff75da222cded9eed1035a685b65673407138e9669ca612aa5ee9b756d3b

also, i still think you should make a `page/node_modules/dat-theme-light` and `page/node_modules/dat-theme-dark` and later on even a basic protocol, e.g.
```js
const dark_theme = require('dark-theme')
const light_theme = require('light-theme')
// ...
var num, mid = 0
document.body.append(home_page({ theme: theme_light }, protocol))

function protocol (send) {
  const PROTOCOL = {
    'theme': change_theme
  }
  listen.id = `${__dirname}:${num++}`
  return listen
  function listen (message) {
    const { head, type, data } = message
    const [by, to, id] = head
    if (to !== listen.id) return console.error('address unknown', message)
    const action = PROTOCOL[type] || invalid
    action(message)
  }
  function invalid (message) { console.error('invalid type', message) }
  async function change_theme ({ head: [to], data: theme_name }) {
    switch (theme_name) {
      case 'light': return send({
        head: [listen.id, to, mid++], type: 'theme', data: light_theme
      })
      case 'dark': return send({
        head: [listen.id, to, mid++], type: 'theme', data: dark_theme
      })
    }
  }
}
```

**Comment by Mehrabbruno** [comment]
- [x] update home_page_v0.0.1
   - `@input` 📦 [`home_page_v0.0.1`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/c25b10717943c1c0a24918885ee44002cb70688f)
   - `@input` 📦 [`navbar_v0.0.4`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-c350355782ad8dbbaf52b78e0ad161dd2952f72c07586109c4f1c597eb82b10a) from #2 
   - [x] read feedback
   - [x] updating theme settings
   - [x] commit everything
   - [x] look into creating a pull request
   - `@output` 📦 [`home_page_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556)


### tasks - `2023.06.03`

- update home_page_v0.0.1 - `1h33min`
   - read feedback - `25min
   - trying to update theme settings - `3h`
   - commit everything - `13min`
   - look into creating a pull request - `12min`
   - updating contract - `1h28min`
   - create - worklog comment, and task - `13min`
   - `@output` 📦 [`home_page_v0.0.2`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556)

---

## worklog 

[worklog-149](https://youtu.be/l0yaPv_6oLI)
[worklog-150](https://youtu.be/BQzQEPrNpbw)

---

## feedback

---

## proposal

**Comment by serapath** [comment]
**feedback `2023.06.08`**
+1 dark theme
+1 lite theme
love them, love colors.
if green is always perceived as the dominant color, that's great.
if pink is always the focus/hover/highlight color, that's great.





## regarding navbar buttons
icons should be svgs, agree,makes it more flexible and themeable,lets convert

could we make the "dat ecosystem" black with green font
but all other buttons green with black font?
=> that way the hexagon leaf logo sticks out more compared to green on green

![navbar](https://imgur.com/vFEKkN5.png)

we need a "hover" color or pattern, maybe:
![hover pattern](https://imgur.com/sIdNo2t.png)
we need an "active" color or pattern, maybe:
![active pattern](https://i.imgur.com/8v3EUzA.png)

...for example, but of course with our exact pink, not some random pink :P


## regarding coding
of course, no semicolons in standardjs.
otherwise, the component instantiation should be moved inside the "home_page" 
```js
function home_page (opts, protocol) {
  const components = [
    cover_app(),
    app_timeline_mini(),
    app_projects_mini(),
    app_about_us(),
    app_footer(),
  ]
  // ....
}
```

The following is legit and means the `home_page` component type has no general styling, but each instance needs custom styling and usually people only use a single instance on their website i guess.
```js
    const sheet = new CSSStyleSheet
    sheet.replaceSync(get_theme(opts.light_theme))
```

but then youdo something interesting,which is hard code specific styles

(and use semicolons :D)
```js
    const body_style = document.body.style;
    Object.assign(body_style, {
        margin: '0',
        padding: '0',
        opacity: `1`,
        backgroundImage: `radial-gradient(${opts.light_theme.primary_color} 2px, ${opts.light_theme.bg_color} 2px)`,
        backgroundSize: `16px 16px`
    });
```
so first this could be re-written as:
```js
document.body.style = `
  margin: 0;
  padding: 0;
  opacity: 1;
  background-image: radial-gradient(${opts.light_theme.primary_color} 2px, ${opts.light_theme.bg_color} 2px);
  background-size: 16px 16px;
`
```
But the above should more properly NEVER be part of a component.
You mutate the `document.body` which is an absolute **no go**

More properly, this code snippet to apply default styling to `document.body.style` should sit in what we call `demo.js` inside the tutorial series and which we can now call `page.js`.
That file is where it all starts and it will require('home-page') as the main component and then do
```js
cosnt home_page = require('home-page')
const page = home_page()

document.body.style = `
  margin: 0;
  padding: 0;
  opacity: 1;
  background-image: radial-gradient(${opts.light_theme.primary_color} 2px, ${opts.light_theme.bg_color} 2px);
  background-size: 16px 16px;
`

document.body.append(page)
```

Now the background image should probably be part of the theme and part of the component instance `page`, ...which means **every app is just a component instance**
...which means if i decided to show our entire app with 20% padding on the body, then the background image pattern would only apply to the inside of my actual home page component.

This is the correct way.
But in our case we will anyway run our home page instance full screen 100% width/height, thus nobody will see that the `document.body` has no background color or image applied.


## regarding protocol messaging
we will refine this over time, but one thing we should initially stick to is a standardized message format, which in verbose looks like this:
```js
function listen (message) {
  
  function format (new_message = {
    head: [from = 'alice', to = 'bob', message_id = 1],
    refs: { cause: message.head }, // reply to received message
    type: 'change_theme',
    data: `.foo { background-color: red; }`
  }) { return new_message }
  
  console.log(format()) // =>
  {
    head: ['alice', 'bob', 1], // first message from alice to bob
    refs: { cause: old_head }, // head of msg to reply to (if none, this message is initiating)
    type: 'change_theme', 
    data: `.foo { background-color: red; }`, // or whatever a change theme message is
    meta: { time, stack }, // we can ignore this, it is auto generated later on
  }
}
```
basically the above shows a full standard format compliant message.
The `meta: { time, stack }` is irrelevant for now. We deal with that later.
Also `refs.cause` is ncie to set if you respond to a message received.
If you can create a new head for each message, that's great, but if that is too
complicated for now, we can focus mostly on
`const message = { type, data }` which are the important bits.
And if a specific component only knows a single message type, then probably even
`const message = { data }` does suffice in that case :-)

```js
    function protocol (message, notify) {
        const { from } = message
        state[from] = { active_state: 'light_theme', notify}
        return listen
    }
    function listen ( message ){
        const {from, active_state} = message
        if ( active_state === 'light_theme' )  {
            let notify = state['navbar-0'].notify
            sheet.replaceSync( get_theme( opts.dark_theme ) )
            Object.assign(body_style, { backgroundImage: `radial-gradient(${opts.dark_theme.primary_color} 2px, ${opts.dark_theme.bg_color} 2px)`, });
            notify( active_state )
        } else {
            let notify = state['navbar-0'].notify
            Object.assign(body_style, { backgroundImage: `radial-gradient(${opts.light_theme.primary_color} 2px, ${opts.light_theme.bg_color} 2px)`, });
            sheet.replaceSync( get_theme( opts.light_theme ) ) 
            notify( active_state )
        }
    }
```

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.17`

- update home_page_v0.0.2 
   - updating page theme function - `1h10min`
   - updating page theme function
   - create - worklog comment, and task- `19min`
   - `@output` 📦 [`home_page_v0.0.3`](https://github.com/dat-ecosystem/dat-ecosystem/pull/8/commits/e6db56e6421edb084f1e7f70088b1fc63c73bf9c#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556)

---

## worklog 

[worklog-154](https://youtu.be/g0IGPcYg5ts)
[worklog-155](https://youtu.be/7paMxUviKQQ)

---

## feedback

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.06.23`

- update home_page_v0.0.3
   - read feedback on discord - `13min`
   - read feedback on home_page and page component - `14min`
   - convert all icons to svg - `2h44min`
   - export all icons to svg with same ratio - `1h7min`
   - updating page theme content and file structure - `53min`
   - create - worklog comment, and task- `16min`
   - `@output` 📦 [`home_page_v0.0.4`](https://github.com/dat-ecosystem/dat-ecosystem/commit/8829064817deabb9dcd64539ecbe395bccc847fc#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556)

---

## worklog 

[worklog-156](https://youtu.be/y8bct5IkZ2Y)

---

## feedback

- All the theme, icons, home_page and page components are coded in these tasks (watch worklog to cover everything)

---

## proposal

**Comment by Mehrabbruno** [comment]
### tasks - `2023.07.06`

- update home_page_v0.0.4 - `7min`
   - update home_page to fit the navigation/toggle protocols
   - create - worklog comment, and task - `11min`
   - @output 📦[`home_page_v0.0.5`](https://github.com/dat-ecosystem/dat-ecosystem/commit/4b62b625ae3933164c59fea7da79c0122c82695a#diff-4ef53874f4193e6493d6355eb53b87b87a3f574878420e9dd2c9c00f2c7fe9cb)

---

## worklog 

[worklog-160](https://youtu.be/vEjAzVv_N4U)

---

## feedback

---

## proposal

**Comment by ninabreznik** [comment]
Thanks for your work. 
Little updates, we could do:
- in the learn about us section we should bring the images infront of the grid (now the dotted grid goes over, making images not nicely visible. We should make it same as in the cover.pdf section)
