### ISSUE TITLE
Update - timeline_card Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#8]
## `todo`

- [x] Update timeline_card_v0.1.0
   - `@input` :package: [`buttons_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/tree/main/src/node_modules/buttons) from #3 
   - [x] update the timeline_card component
   - `@output` :package: [`timeline_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-card/timeline-card.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/7#issuecomment-1913305945)

---

- [ ] Finalize timeline_card_v0.1.?
   - [ ] code timeline_card component
   - `@output` :package: `timeline_card_v0.1.?` from `comment`
   - next #8

**Comment by alyhxn** [comment]
### tasks - `2024.01.27`

- Update timeline_card_v0.1.0
   - update the timeline_card component
   - `@output` :package: [`timeline_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-card/timeline-card.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
