### ISSUE TITLE
Update - app_timeline_mini Component

### ISSUE THREAD

**Issue by alyhxn** [dat-ecosystem/dat-ecosystem#9]
## `todo`

- [x] Update app_timeline_mini_v0.1.0
  - `@input` :package: [`window_bar_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/window-bar/window-bar.js) from #4 
  - `@input` :package: [`timeline_card_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/timeline-card/timeline-card.js) from #8 
  - [x] update app_timeline_mini component
  - `@output` :package:  [`app_timeline_mini_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-timeline-mini/app-timeline-mini.js) from [comment](https://github.com/Mehrabbruno/dat-ecosystem/issues/8#issuecomment-1913425187)

---

- [ ] Finalize app_timeline_mini_v0.1.?
   - [ ] code app_timeline_mini
   - `@output` :package: [`app_timeline_mini_v0.1.?`] from `comment`
   - next #11

**Comment by alyhxn** [comment]
### tasks - `2024.01.28`

- Update app_timeline_mini_v0.1.0
  - update the app_timeline_mini component
  - `@output` :package:  [`app_timeline_mini_v0.1.1`](https://github.com/dat-ecosystem/dat-ecosystem/blob/main/src/node_modules/app-timeline-mini/app-timeline-mini.js)

---

### worklog

---

### feedback
Initialized the issue

---

### proposals
